export const SERVER_WORKSPACE_MESSAGE_TYPES = [
  'checkpoint.written',
  'codemap.file_event',
  'codemap.index_updated',
  'codemap.tool_executed',
  'codemap.tool_started',
  'file.saved',
  'files.list',
  'files.read',
  'files.tree',
  'files.written',
  'git.changes',
  'git.diff',
  'git.info',
  'process.list',
  'projects.added',
  'projects.list',
  'projects.selected',
  'terminal.exit',
  'terminal.output',
  'working_dir.changed',
  'worktree.cleanup_result',
  'worktree.diff_result',
  'worktree.event',
  'worktree.merge_result',
  'worktree.orphans',
  'worktree.state',
] as const;

export const SERVER_CONFIGURATION_MESSAGE_TYPES = [
  'auth.oauth.status',
  'diag.get',
  'key.operation_result',
  'prefs.updated',
  'provider.catalog',
  'provider.models',
  'provider.probe',
  'provider.status.snapshot',
  'providers.saved',
] as const;
