export const SERVER_GOAL_MESSAGE_TYPES = [
  'budget.decision',
  'budget.threshold_reached',
  'coordinator.stats',
  'coordinator.status',
  'eternal.iteration',
  'fleet.concurrency_update',
  'goal-state.updated',
  'goal.assess.result',
  'goal.list',
  'goal.paused',
  'goal.resumed',
  'goal.saved',
  'goal.error',
  'goal.stopped',
  'goal.failed',
  'goal.completed',
  'goal.cleared',
  'goal.reverted',
  'goal.progress',
  'goal.state',
  'in_flight.ended',
  'in_flight.started',
  'plan.updated',
  'task.completed',
  'task.failed',
  'task.pending',
  'task.started',
  'tasks.updated',
  'todos.cleared',
  'todos.updated',
] as const;

export const SERVER_SDD_MESSAGE_TYPES = [
  'kanban.task.activity',
  'sdd.board.lifecycle_result',
  'sdd.board.list',
  'sdd.board.snapshot',
  'sdd.run.started',
  'sdd.spec.agent_text',
  'sdd.spec.error',
  'sdd.spec.snapshot',
  'specs.detail',
  'specs.list',
] as const;

export const SERVER_AUTOMATION_MESSAGE_TYPES = [
  'consensus.vote_cast',
  'consensus.vote_initiated',
  'consensus.vote_resolved',
  'cron.job_fired',
  'cron.snapshot',
  'techstack.job.cancelled',
  'techstack.job.failed',
  'techstack.job.progress',
  'techstack.job.started',
  'techstack.report.delivered',
  'techstack.report.ready',
  'techstack.snapshot.updated',
  'techstack.workspace.completed',
] as const;
