/**
 * Ratchet: type-module-cycle exceptions in `architecture/exceptions.json` must
 * each match an active cycle in the current SCC scan.
 *
 * Background: card4c-health.txt reported "1 unexcepted module cycle(s) —
 * ARCH-CYCLE-TYPE-23: exception no longer matches an active cycle". That means
 * the cycle was fixed but the exception was never deleted. Future card4c
 * reports would keep flagging this as a noise signal that obscures real
 * exceptions. This test uses the architecture scanner directly rather than an
 * ignored `.reports` artifact so `pnpm test` does not depend on local evidence
 * generated by another command.
 */

import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  buildArchitectureHealth,
  loadArchitectureInputs,
  renderArchitectureHealthMarkdown,
} from '../../../../scripts/lib/architecture-health.mjs';

const REPO_ROOT = path.resolve(fileURLToPath(new URL('../../../..', import.meta.url)));
const EXCEPTIONS = path.resolve(REPO_ROOT, 'architecture/exceptions.json');

interface ExceptionRecord {
  id: string;
  kind: string;
  members: string[];
  reason?: string;
}

async function loadExceptions(): Promise<{ exceptions: ExceptionRecord[] }> {
  const text = await fs.readFile(EXCEPTIONS, 'utf8');
  return JSON.parse(text) as { exceptions: ExceptionRecord[] };
}

const architectureReportPromise = (async () => {
  const { registry, exceptions, hotspots } = await loadArchitectureInputs(REPO_ROOT);
  return buildArchitectureHealth({
    repoRoot: REPO_ROOT,
    registry,
    exceptions,
    hotspots,
  });
})();

async function loadTypeCycleMembers(): Promise<Set<string>> {
  const report = await architectureReportPromise;
  const members = new Set<string>();
  for (const cycle of report.cycles.type as Array<{ members: string[] }>) {
    for (const member of cycle.members) members.add(member);
  }
  return members;
}

describe('stale architecture-exception cleanup', () => {
  it('current architecture report renders the type-cycle section', {
    timeout: 180_000,
  }, async () => {
    const report = await architectureReportPromise;
    const markdown = renderArchitectureHealthMarkdown(report);
    expect(markdown).toContain('Type-inclusive module cycles');
  });

  it('every type-module-cycle exception member appears in a current card4c cycle', {
    timeout: 180_000,
  }, async () => {
    const { exceptions } = await loadExceptions();
    const activeMembers = await loadTypeCycleMembers();
    const typeCycleExceptions = exceptions.filter((e) => e.kind === 'type-module-cycle');

    if (typeCycleExceptions.length === 0) {
      // No exceptions to verify against — pass through, the guard is
      // satisfied vacuously.
      return;
    }

    const stale: string[] = [];
    for (const exception of typeCycleExceptions) {
      // An exception is "stale" when NONE of its members appear in any
      // current cycle block (i.e. the SCC has been fully broken).
      const anyMemberMatches = exception.members.some((m) => activeMembers.has(m));
      if (!anyMemberMatches) {
        stale.push(
          `${exception.id}: no member appears in current card4c cycles — ` +
            'remove the exception or document why it is preserved.',
        );
      }
    }
    expect(stale, stale.join('\n')).toEqual([]);
  });

  it('every exception id is unique (defensive against duplicate SCC entries)', async () => {
    const { exceptions } = await loadExceptions();
    const ids = exceptions.map((e) => e.id);
    const unique = new Set(ids);
    expect(unique.size).toBe(ids.length);
  });
});
