export const KANBAN_COMMAND_HELP = [
  'Usage:',
  '  /kanban                        List all kanban boards',
  '  /kanban open                   Open the TUI kanban panel',
  '  /kanban create <title>         Create a new board',
  '  /kanban duplicate <boardId> [title]  Duplicate a board',
  '  /kanban show <boardId>         Show board details (columns + tasks)',
  '  /kanban delete <boardId>       Delete a board',
  '  /kanban prune [days] [--all] [--yes]  Delete stale boards (dry-run without --yes)',
  '  /kanban rename <boardId> <t>   Rename a board',
  '  /kanban snapshot [boardId]     Show agent queue snapshot',
  '',
  '  /kanban task add <boardId> <title>          Add a task to board',
  '  /kanban task <boardId>                     List tasks on a board',
  '  /kanban task ready [boardId]               List dependency-ready tasks',
  '  /kanban task claim [boardId] <agent>       Atomically claim next ready task',
  '  /kanban task release <boardId> <taskId>    Release a queued/running claim',
  '  /kanban task show <boardId> <taskId>       Show task details',
  '  /kanban task move <boardId> <taskId> <col>  Move task to column',
  '  /kanban task done <boardId> <taskId>        Mark task completed',
  '  /kanban task block <boardId> <taskId>       Mark task blocked',
  '  /kanban task remove <boardId> <taskId>      Delete a task',
  '  /kanban task split <boardId> <taskId> <a> | <b>  Split task into children',
  '  /kanban task merge <boardId> <taskA,taskB> <title> Merge tasks',
  '  /kanban task chain <boardId> <taskA> <taskB> [...] Ordered task chain',
  '  /kanban task copy <fromBoard> <taskId> <toBoard> [columnId]',
  '  /kanban task transfer <fromBoard> <taskId> <toBoard> [columnId]',
  '',
  '  /kanban task priority <boardId> <taskId> <p>   Set priority',
  '  /kanban task assign <boardId> <taskId> <agent> [--provider=p --model=m --fallback=f]',
  '  /kanban task dispatch <boardId> <taskId> [--provider=p --model=m --name=n]',
  '  /kanban task depend <boardId> <taskId> <depId>  Add dependency',
  '  /kanban task metric add <boardId> <taskId> <name> [target] [unit]',
  '  /kanban task metric set <boardId> <taskId> <metricId> <current> [met|missed|waived|pending]',
  '  /kanban task note <boardId> <taskId> <text>      Add task note',
  '',
  '  /kanban task check add <boardId> <taskId> <desc>  Add success check',
  '',
  '  /kanban generate <description>     Auto-generate board from text',
  '  /kanban export <boardId>           Export board as markdown',
  '  /kanban graph export <boardId> [graphId]  Save board as SDD TaskGraph',
  '  /kanban graph import <graphId>           Create board from SDD TaskGraph',
  '  /kanban graph sync <boardId> <graphId>   Sync board from SDD TaskGraph',
  '  /kanban deps <boardId> <taskId>    Show dependency chain',
].join('\n');
