import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'auto-doc': 'src/auto-doc/index.ts',
    'git-autocommit': 'src/git-autocommit/index.ts',
    'shell-check': 'src/shell-check/index.ts',
    'cost-tracker': 'src/cost-tracker/index.ts',
    'file-watcher': 'src/file-watcher/index.ts',
    'cron': 'src/cron/index.ts',
    'template-engine': 'src/template-engine/index.ts',
    'semver-bump': 'src/semver-bump/index.ts',
    'secret-scanner': 'src/secret-scanner/index.ts',
    'todo-tracker': 'src/todo-tracker/index.ts',
    'token-budget': 'src/token-budget/index.ts',
    'lint-gate': 'src/lint-gate/index.ts',
    'branch-guard': 'src/branch-guard/index.ts',
    'diff-summary': 'src/diff-summary/index.ts',
    'commit-validator': 'src/commit-validator/index.ts',
    'format-on-save': 'src/format-on-save/index.ts',
    'test-runner-gate': 'src/test-runner-gate/index.ts',
    'import-organizer': 'src/import-organizer/index.ts',
    'todo-listener': 'src/todo-listener/index.ts',
    'session-recap': 'src/session-recap/index.ts',
    'spec-linker': 'src/spec-linker/index.ts',
    'loop-breaker': 'src/loop-breaker/index.ts',
    'path-guard': 'src/path-guard/index.ts',
    'context-pins': 'src/context-pins/index.ts',
    'checkpoint': 'src/checkpoint/index.ts',
    'error-lens': 'src/error-lens/index.ts',
    'dep-guard': 'src/dep-guard/index.ts',
    'config-validator': 'src/config-validator/index.ts',
    'notify-hub': 'src/notify-hub/index.ts',
    'changelog-writer': 'src/changelog-writer/index.ts',
    'injection-shield': 'src/injection-shield/index.ts',
    'llm-cache': 'src/llm-cache/index.ts',
    'model-router': 'src/model-router/index.ts',
    'prompt-firewall': 'src/prompt-firewall/index.ts',
    'auto-escalate': 'src/auto-escalate/index.ts',
    'token-throttle': 'src/token-throttle/index.ts',
  },
  format: ['esm'],
  dts: true,
  splitting: false,
  treeshake: true,
  clean: true,
  external: ['@wrongstack/core'],
});