import type { WSServerMessage } from '@/types';
import {
  handleCompactionFailed,
  handleContextCompacted,
  handleContextDebug,
  handleContextMaxContext,
  handleContextModeChanged,
  handleContextModesList,
  handleContextPct,
  handleContextRepaired,
  handleError,
  handleKeyOperationResult,
  handleModelSwitchResult,
  handleSessionResumeProgress,
  handleTokenCostEstimateUnavailable,
  handleTokenThreshold,
  handleTrustPersisted,
} from './session-context-handlers';
import {
  handleCheckpointWritten,
  handleDelegateCompleted,
  handleDelegateStarted,
  handleInFlightEnded,
  handleInFlightStarted,
  handleIterationCompleted,
  handleIterationLimitReached,
  handleProviderActiveBlocked,
  handleProviderAuditHistory,
  handleProviderError,
  handleProviderFallback,
  handleProviderFallbackPending,
  handleProviderModelSwitched,
  handleProviderResponse,
  handleProviderRetry,
  handleProviderStatusChanged,
  handleProviderStatusSnapshot,
  handleProviderStreamError,
  handleSessionDamaged,
  handleSessionEnd,
  handleSessionRewound,
  handleSessionsList,
  handleToolLoopDetected,
} from './session-execution-handlers';

export {
  flushThinkingLogForCurrentIteration,
  handleCompactionFailed,
  handleContextCompacted,
  handleContextDebug,
  handleContextMaxContext,
  handleContextModeChanged,
  handleContextModesList,
  handleContextPct,
  handleContextRepaired,
  handleError,
  handleKeyOperationResult,
  handleModelSwitchResult,
  handleSessionResumeProgress,
  handleTokenCostEstimateUnavailable,
  handleTokenThreshold,
  handleTrustPersisted,
  warnedCostModels,
} from './session-context-handlers';
export {
  handleCheckpointWritten,
  handleDelegateCompleted,
  handleDelegateStarted,
  handleInFlightEnded,
  handleInFlightStarted,
  handleIterationCompleted,
  handleIterationLimitReached,
  handleProviderActiveBlocked,
  handleProviderAuditHistory,
  handleProviderError,
  handleProviderFallback,
  handleProviderFallbackPending,
  handleProviderResponse,
  handleProviderRetry,
  handleProviderStatusChanged,
  handleProviderStatusSnapshot,
  handleProviderStreamError,
  handleSessionDamaged,
  handleSessionEnd,
  handleSessionRewound,
  handleSessionsList,
  handleToolLoopDetected,
  truncateLine,
} from './session-execution-handlers';
export {
  contentToToolResult,
  handleSessionStart,
  hydrateReplayMessages,
  isRoutePinnedView,
  providerResponseText,
  type ReplayMessage,
  replayMessageId,
  replayTimestamp,
  sessionRouteIdentifier,
} from './session-replay-handlers';

export const sessionHandlerMap: Partial<Record<string, (msg: WSServerMessage) => void>> = {
  'context.debug': handleContextDebug,
  'key.operation_result': handleKeyOperationResult,
  'model.switch_result': handleModelSwitchResult,
  'context.compacted': handleContextCompacted,
  'compaction.failed': handleCompactionFailed,
  'provider.response': handleProviderResponse,
  'iteration.completed': handleIterationCompleted,
  'iteration.limit_reached': handleIterationLimitReached,
  'provider.retry': handleProviderRetry,
  'provider.error': handleProviderError,
  'provider.fallback': handleProviderFallback,
  'provider.fallback_pending': handleProviderFallbackPending,
  'provider.model_switched': handleProviderModelSwitched,
  'provider.status_changed': handleProviderStatusChanged,
  'provider.active_blocked': handleProviderActiveBlocked,
  'provider.stream_error': handleProviderStreamError,
  'tool.loop_detected': handleToolLoopDetected,
  'delegate.started': handleDelegateStarted,
  'delegate.completed': handleDelegateCompleted,
  'trust.persisted': handleTrustPersisted,
  'context.repaired': handleContextRepaired,
  'ctx.pct': handleContextPct,
  'ctx.max_context': handleContextMaxContext,
  'token.threshold': handleTokenThreshold,
  'token.cost_estimate_unavailable': handleTokenCostEstimateUnavailable,
  'session.end': handleSessionEnd,
  'session.resume_progress': handleSessionResumeProgress,
  'session.damaged': handleSessionDamaged,
  'session.rewound': handleSessionRewound,
  'checkpoint.written': handleCheckpointWritten,
  'in_flight.started': handleInFlightStarted,
  'in_flight.ended': handleInFlightEnded,
  'context.modes.list': handleContextModesList,
  'context.mode.changed': handleContextModeChanged,
  'sessions.list': handleSessionsList,
  'provider.status.snapshot': handleProviderStatusSnapshot,
  'provider.audit.history': handleProviderAuditHistory,
  error: handleError,
};
