import type { Theme } from '../theme-types.js';
import { baseTheme } from './base.js';

/** 2 palettes: contrast-max, colorblind-safe. */
export const accessiblePresets = {
  'contrast-max': Object.freeze({
    ...baseTheme,
    textPrimary: '#ffffff',
    textSecondary: '#eaeaea',
    textMuted: '#c2c2c2',
    brandPrimary: '#ffd400',
    brandAccent: '#ff6ec7',
    surface: '#000000',
    surfaceRaised: '#1a1a1a',
    accent: '#4db8ff',
    user: '#ffd400',
    assistant: '#4db8ff',
    tool: '#b388ff',
    success: '#00e676',
    warn: '#ffab00',
    error: '#ff5252',
    borderDefault: '#9a9a9a',
    borderSubtle: '#5a5a5a',
    borderActive: '#ffd400',
    brand: '#ff6ec7',
    diffAddBg: '#00733b',
    diffDelBg: '#7c2828',
    monitor: { fleet: '#4db8ff', agents: '#ff6ec7', worktree: '#00e676', phase: '#4db8ff' },
  }),
  'colorblind-safe': Object.freeze({
    ...baseTheme,
    textPrimary: '#eaeaea',
    textSecondary: '#c2c9d6',
    textMuted: '#9aa4b8',
    brandPrimary: '#ff9e3d',
    brandAccent: '#c58fff',
    surface: '#171b21',
    surfaceRaised: '#242a33',
    accent: '#4d9de0',
    user: '#ff9e3d',
    assistant: '#4d9de0',
    tool: '#7bc9ff',
    success: '#00a6a6',
    warn: '#ffd166',
    error: '#e8505b',
    borderDefault: '#6a7280',
    borderSubtle: '#333941',
    borderActive: '#ffd166',
    brand: '#c58fff',
    diffAddBg: '#0e5155',
    diffDelBg: '#5e2d35',
    monitor: { fleet: '#4d9de0', agents: '#c58fff', worktree: '#00a6a6', phase: '#4d9de0' },
  }),
} satisfies Record<string, Theme>;
