import type { Theme } from '../theme-types.js';
import { baseTheme } from './base.js';

/** 2 palettes: ayu-dark, ayu-mirage. */
export const ayuPresets = {
  'ayu-dark': Object.freeze({
    ...baseTheme,
    textPrimary: '#b3b1a9',
    textSecondary: '#9a9890',
    textMuted: '#828689',
    brandPrimary: '#ff8f40',
    brandAccent: '#d4b5ff',
    surface: '#0f1419',
    surfaceRaised: '#1a222c',
    accent: '#59c2ff',
    user: '#ffaa33',
    assistant: '#95e6cb',
    tool: '#59c2ff',
    success: '#aad94c',
    warn: '#ffaa33',
    error: '#f07178',
    borderDefault: '#3d414c',
    borderSubtle: '#2a2f3a',
    borderActive: '#ff8f40',
    brand: '#d4b5ff',
    diffAddBg: '#1c2a1f',
    diffDelBg: '#2e1c20',
    monitor: { fleet: '#59c2ff', agents: '#d4b5ff', worktree: '#aad94c', phase: '#59c2ff' },
  }),
  'ayu-mirage': Object.freeze({
    ...baseTheme,
    textPrimary: '#cbccc6',
    textSecondary: '#a9abaa',
    textMuted: '#828689',
    brandPrimary: '#ff8f40',
    brandAccent: '#d4bfff',
    surface: '#1f2430',
    surfaceRaised: '#272e3d',
    accent: '#73d0ff',
    user: '#ff8f40',
    assistant: '#73d0ff',
    tool: '#95e6cb',
    success: '#bae67e',
    warn: '#ffd76d',
    error: '#f28779',
    borderDefault: '#4a5162',
    borderSubtle: '#292e3b',
    borderActive: '#ffcc66',
    brand: '#d4bfff',
    diffAddBg: '#37423c',
    diffDelBg: '#4e3a40',
    monitor: { fleet: '#73d0ff', agents: '#d4bfff', worktree: '#bae67e', phase: '#73d0ff' },
  }),
} satisfies Record<string, Theme>;
