import type { Theme } from '../theme-types.js';
import { baseTheme } from './base.js';

/** 2 palettes: material-ocean, palenight. */
export const materialPresets = {
  'material-ocean': Object.freeze({
    ...baseTheme,
    textPrimary: '#a6accd',
    textSecondary: '#8f93a2',
    textMuted: '#6b7394',
    brandPrimary: '#f78c6c',
    brandAccent: '#c792ea',
    surface: '#0f111a',
    surfaceRaised: '#1a1c25',
    accent: '#89ddff',
    user: '#ffcb6b',
    assistant: '#89ddff',
    tool: '#82aaff',
    success: '#c3e88d',
    warn: '#ffcb6b',
    error: '#f07178',
    borderDefault: '#3b3f51',
    borderSubtle: '#2d3147',
    borderActive: '#89ddff',
    brand: '#c792ea',
    diffAddBg: '#17301f',
    diffDelBg: '#331b21',
    monitor: { fleet: '#89ddff', agents: '#c792ea', worktree: '#c3e88d', phase: '#82aaff' },
  }),
  palenight: Object.freeze({
    ...baseTheme,
    textPrimary: '#babed8',
    textSecondary: '#a6accd',
    textMuted: '#7d86ad',
    brandPrimary: '#f78c6c',
    brandAccent: '#c792ea',
    surface: '#292d3e',
    surfaceRaised: '#34324a',
    accent: '#82aaff',
    user: '#ffcb6b',
    assistant: '#89ddff',
    tool: '#82aaff',
    success: '#c3e88d',
    warn: '#ffcb6b',
    error: '#f07178',
    borderDefault: '#4a4f6a',
    borderSubtle: '#454a63',
    borderActive: '#82aaff',
    brand: '#c792ea',
    diffAddBg: '#2b4033',
    diffDelBg: '#43293a',
    monitor: { fleet: '#82aaff', agents: '#c792ea', worktree: '#c3e88d', phase: '#89ddff' },
  }),
} satisfies Record<string, Theme>;
