import type { Theme } from '../theme-types.js';
import { baseTheme } from './base.js';

/** 3 palettes: tokyo-night, tokyo-night-storm, tokyo-night-moon. */
export const tokyoNightPresets = {
  'tokyo-night': Object.freeze({
    ...baseTheme,
    textPrimary: '#c0caf5',
    textSecondary: '#a9b1d6',
    textMuted: '#5a6390',
    brandPrimary: '#ff9e64',
    brandAccent: '#bb9af7',
    surface: '#16161e',
    surfaceRaised: '#1d1f2e',
    accent: '#7dcfff',
    user: '#e0af68',
    assistant: '#7dcfff',
    tool: '#73daca',
    success: '#9ece6a',
    warn: '#e0af68',
    error: '#f7768e',
    borderDefault: '#414868',
    borderSubtle: '#24283b',
    borderActive: '#ff9e64',
    brand: '#bb9af7',
    diffAddBg: '#1c3326',
    diffDelBg: '#37202b',
    monitor: { fleet: '#7dcfff', agents: '#bb9af7', worktree: '#9ece6a', phase: '#7dcfff' },
  }),
  'tokyo-night-storm': Object.freeze({
    ...baseTheme,
    textPrimary: '#c0caf5',
    textSecondary: '#a9b1d6',
    textMuted: '#6b76a8',
    brandPrimary: '#ff9e64',
    brandAccent: '#bb9af7',
    surface: '#1f2335',
    surfaceRaised: '#24283b',
    accent: '#7aa2f7',
    user: '#e0af68',
    assistant: '#7dcfff',
    tool: '#73daca',
    success: '#9ece6a',
    warn: '#e0af68',
    error: '#f7768e',
    borderDefault: '#3b4261',
    borderSubtle: '#3a405f',
    borderActive: '#7aa2f7',
    brand: '#bb9af7',
    diffAddBg: '#20372c',
    diffDelBg: '#3b2331',
    monitor: { fleet: '#7aa2f7', agents: '#bb9af7', worktree: '#9ece6a', phase: '#7dcfff' },
  }),
  'tokyo-night-moon': Object.freeze({
    ...baseTheme,
    textPrimary: '#c8d3f5',
    textSecondary: '#a5b6cf',
    textMuted: '#636e8d',
    brandPrimary: '#ff966c',
    brandAccent: '#c099ff',
    surface: '#1e2030',
    surfaceRaised: '#2a2d45',
    accent: '#82aaff',
    user: '#ffc777',
    assistant: '#82aaff',
    tool: '#c099ff',
    success: '#c3e88d',
    warn: '#ffc777',
    error: '#ff757f',
    borderDefault: '#3b4261',
    borderSubtle: '#3a405f',
    borderActive: '#82aaff',
    brand: '#c099ff',
    diffAddBg: '#1d3627',
    diffDelBg: '#3d1e28',
    monitor: { fleet: '#82aaff', agents: '#c099ff', worktree: '#c3e88d', phase: '#ff966c' },
  }),
} satisfies Record<string, Theme>;
