/**
 * Factory for the fallback gate function.
 *
 * The gate is injected into `createFallbackModelExtension` as `fallbackGate`.
 * When the fallback chain is about to engage, the gate:
 *
 * 1. Registers a `provider.fallback_choice` listener keyed on `requestId`.
 * 2. Emits `provider.fallback_pending` on the EventBus — carrying the
 *    candidate list, countdown duration, and the caller-supplied
 *    `requestId` (generated by the fallback-model extension so the
 *    `provider.fallback` completion event can share the same id).
 * 3. Waits for the choice event (the user manually picked a model), OR for
 *    the countdown timer to expire (auto-switch to the chain head).
 * 4. Resolves with the chosen model reference, or `null` for auto-switch.
 *
 * Registration happens BEFORE the emit so a same-tick choice reply from a
 * synchronous EventBus listener (test harness, automated UI pick) is not
 * dropped.
 *
 * An absolute deadline (autoSwitchSeconds * 1.5) ensures the gate never
 * hangs indefinitely even if neither signal arrives (headless mode, no UI
 * listener, etc.).
 */
import type { FallbackGateFn } from '@wrongstack/core/agent';
import type { EventBus } from '@wrongstack/core/kernel';

/**
 * Create a fallback gate that emits `provider.fallback_pending` and waits
 * for a `provider.fallback_choice` event or the countdown timer.
 */
export function createFallbackGate(_events: EventBus): FallbackGateFn {
  const gateFn: FallbackGateFn = (params) => {
    const { events: bus, sessionId, from, status, candidates, autoSwitchSeconds, requestId } =
      params;

    return runGate(bus, { sessionId, from, status, candidates, autoSwitchSeconds, requestId });
  };
  return gateFn;
}

/**
 * Shared gate runner — subscribes BEFORE emitting to avoid dropping a
 * same-tick choice reply.
 */
function runGate(
  events: EventBus,
  gateParams: {
    sessionId: string | undefined;
    from: { providerId: string; model: string };
    status: number;
    candidates: Array<{ providerId: string; model: string }>;
    autoSwitchSeconds: number;
    requestId: string;
  },
): Promise<{ providerId: string; model: string } | null> {
  const { sessionId, from, status, candidates, autoSwitchSeconds, requestId } = gateParams;

  // ── No-listener fast-path ─────────────────────────────────────────────
  // The gate exists so a UI can show a modal and let the user pick a
  // fallback model. If no component subscribes to `provider.fallback_pending`,
  // no modal can render and no `provider.fallback_choice` reply will ever
  // arrive — waiting out the countdown would add pure latency to every
  // fallback engagement in headless/scripted/CI runs and in any session
  // where the modal UI is not wired. Resolve `null` (auto-switch to the
  // chain head) immediately, restoring the pre-gate behavior.
  //
  // `listenerCount` counts ONLY named listeners for this exact event.
  // Wildcard forwarders — the Chronicle `onAny` bridge, FleetBus
  // `onPattern('*')` forwarding — must not count as a modal surface: they
  // receive the emit but cannot render a picker or reply with a choice.
  if (events.listenerCount('provider.fallback_pending') === 0) {
    return Promise.resolve(null);
  }

  return new Promise((resolve) => {
    let settled = false;
    let timer: ReturnType<typeof setTimeout> | undefined;
    let deadline: ReturnType<typeof setTimeout> | undefined;

    const cleanup = () => {
      if (timer) clearTimeout(timer);
      if (deadline) clearTimeout(deadline);
      events.off('provider.fallback_choice', handler);
    };

    const finish = (result: { providerId: string; model: string } | null) => {
      if (settled) return;
      settled = true;
      cleanup();
      resolve(result);
    };

    // ── Choice handler (registered BEFORE emit) ──────────────────
    // Accepts a manual pick ({ providerId, model }) or an auto-switch
    // signal ({ autoSwitch: true }) from the UI's countdown expiry.
    const handler = (payload: unknown) => {
      const p = payload as {
        requestId?: unknown;
        providerId?: unknown;
        model?: unknown;
        autoSwitch?: unknown;
      };
      if (p?.requestId !== requestId) return;
      if (p.autoSwitch === true) {
        finish(null);
        return;
      }
      if (typeof p.providerId === 'string' && typeof p.model === 'string') {
        finish({ providerId: p.providerId, model: p.model });
      }
    };
    events.on('provider.fallback_choice', handler);

    // ── Safety deadline only ─────────────────────────────────────
    // The UI owns the countdown and sends `provider.fallback_choice`
    // when it expires or the user picks. This 1.5× deadline is a
    // safety net for headless mode (no UI listener) or a dropped
    // choice event — it resolves null (auto-switch to chain head).
    // Scheduled BEFORE emit so cleanup has it assigned on same-tick.
    deadline = setTimeout(() => finish(null), Math.round(autoSwitchSeconds * 1500));

    // ── Emit the pending event so all UI surfaces show the modal ──
    events.emit('provider.fallback_pending', {
      ...(sessionId ? { sessionId } : {}),
      from,
      status,
      candidates,
      autoSwitchSeconds,
      requestId,
      timestamp: Date.now(),
    });
  });
}
