// Generated by scripts/generate-plugin-projections.mjs. Do not edit.
export const OFFICIAL_PLUGIN_AUDIT_ENTRIES = [
  {
    name: 'agent-handoff',
    risk: 'medium',
    summary:
      'Listens for subagent.done events and posts structured handoff notes to the project mailbox',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'cost-tracker',
    risk: 'low',
    summary: 'Tracks LLM token usage and estimated cost per session with per-model breakdown',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'file-watcher',
    risk: 'medium',
    summary: 'Watches project files and emits events when changes occur (add, change, delete)',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'git-autocommit',
    risk: 'high',
    summary: 'AI-powered git staging and conventional commit message generation',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'auto-doc',
    risk: 'medium',
    summary: 'Auto-generates JSDoc/TSDoc comments for functions, classes, types, and interfaces',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'shell-check',
    risk: 'low',
    summary:
      'Runs shellcheck analysis on bash/shell scripts and surfaces issues with severity levels',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'cron',
    risk: 'medium',
    summary: 'Schedules recurring tasks using beforeIteration/afterIteration extension hooks',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'template-engine',
    risk: 'medium',
    summary: 'Expands file templates with variable substitution, conditionals, and loops',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'semver-bump',
    risk: 'high',
    summary: 'Conventional-commit-driven semver version bumps with changelog generation',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'secret-scanner',
    risk: 'high',
    summary:
      'Pre-tool hook that blocks (or optionally redacts) tools whose arguments contain plaintext credentials',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'todo-tracker',
    risk: 'low',
    summary: 'Persistent, project-scoped todo backlog that survives across sessions',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'token-budget',
    risk: 'medium',
    summary:
      'Enforces a per-session token budget — warns at a threshold and stops the agent loop when the limit is hit',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'lint-gate',
    risk: 'medium',
    summary:
      'Pre-tool hook that runs biome/eslint on would-be file content before write or edit commits',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'branch-guard',
    risk: 'high',
    summary:
      'Pre-tool hook that blocks commits, pushes, and merges to protected branches (default: main, master)',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'diff-summary',
    risk: 'low',
    summary:
      'PostToolUse hook that injects a compact git diff into the LLM context after every write or edit',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'commit-validator',
    risk: 'medium',
    summary:
      'PreToolUse hook that validates conventional-commit format before git_autocommit or bash git commit runs',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'format-on-save',
    risk: 'medium',
    summary:
      'PostToolUse hook that runs biome format --write on the file after every write or edit',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'test-runner-gate',
    risk: 'medium',
    summary:
      'PostToolUse hook that runs the relevant test file after every write or edit to a source file',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'import-organizer',
    risk: 'medium',
    summary:
      'PostToolUse hook that re-sorts and de-duplicates imports in a file after every write or edit',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'knowledge-graph',
    risk: 'low',
    summary:
      'Accumulates structured (subject, relation, object) facts about the project and queries them across sessions',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'todo-listener',
    risk: 'low',
    summary:
      'PostToolUse hook on `todo` tool — broadcasts a status update to the project mailbox so other agents can see what this one is working on',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'session-recap',
    risk: 'low',
    summary:
      'Stop hook that posts a one-page session summary (tokens, tools, commits, last activity) to the project mailbox',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'spec-linker',
    risk: 'low',
    summary:
      'Markdown link auditor for plugin references. PostToolUse surfaces unlinked references; PreToolUse on `write` (autoFix) wraps them in markdown links via modifiedInput.',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'loop-breaker',
    risk: 'low',
    summary:
      'Detects runaway tool-call loops (identical repeats and A-B-A-B oscillation) — warns the model, then blocks',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'path-guard',
    risk: 'medium',
    summary:
      'Blocks or warns about writes, edits, and destructive shell commands touching protected paths (lockfiles, .env, .git, migrations)',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'process-guard',
    risk: 'high',
    summary:
      'Blocks kill commands (taskkill, Stop-Process, kill, pkill, wmic) that target active WrongStack processes or their host terminals.',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'context-pins',
    risk: 'low',
    summary:
      'Pin durable facts into the system prompt (pin_add/pin_remove/pin_list) — pins survive compaction and persist across sessions',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'checkpoint',
    risk: 'medium',
    summary:
      'In-session file snapshots: auto-captures content before every write/edit and restores any pre-edit state on demand',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'error-lens',
    risk: 'low',
    summary:
      'Distills failed command output into a compact digest (error line + project stack frames) and flags repeated failures',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'dep-guard',
    risk: 'medium',
    summary:
      'Supervises dependency installs: blocks deny-listed packages, flags typosquat lookalikes, and optionally warns on unpinned versions',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'config-validator',
    risk: 'low',
    summary:
      'Validates JSON/JSONC/YAML/TOML files right after write/edit and reports syntax problems in the same turn',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'notify-hub',
    risk: 'medium',
    summary:
      'POSTs session events (stop, tool errors, budget thresholds) and ad-hoc notify_send messages to a configurable webhook',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'changelog-writer',
    risk: 'low',
    summary:
      'Collects session work (commits, edits, manual notes) and writes Keep-a-Changelog entries under [Unreleased] on demand',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'injection-shield',
    risk: 'low',
    summary:
      'Scans tool output (fetched pages, files) for prompt-injection patterns and warns the model that content is data, not instructions',
    defaultState: 'active',
    canDisable: true,
  },
  {
    name: 'llm-cache',
    risk: 'medium',
    summary:
      'Caches identical provider requests and short-circuits the provider call on a hit (wrapProviderRunner). Opt-in; deterministic-only by default.',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'model-router',
    risk: 'medium',
    summary:
      'Routes each provider call to a different model by declarative size/tool rules (wrapProviderRunner). Opt-in; dry-run by default; routes within the active provider only.',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'pr-drafter',
    risk: 'low',
    summary:
      'Collects session work (commits, edited files, diff) and drafts a pull-request description',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'prompt-firewall',
    risk: 'high',
    summary:
      'Scans the provider wire for credential leaks before context reaches the LLM API (wrapProviderRunner); redact/warn/block. Opt-in; redact by default.',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'auto-escalate',
    risk: 'medium',
    summary:
      'On retryable provider errors, retries the turn with the next model in an escalation ladder (onError). Opt-in; defers to default recovery otherwise.',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'test-coverage-gate',
    risk: 'medium',
    summary: 'PostToolUse hook that detects test coverage regressions after source-file edits',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'type-gate',
    risk: 'medium',
    summary:
      'PostToolUse hook that runs TypeScript type-checking after every write or edit to a source file',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'token-throttle',
    risk: 'medium',
    summary:
      'Rolling-window tokens/min budget that delays provider calls to stay under a rate limit (wrapProviderRunner). Opt-in; delay capped by maxDelayMs.',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'plugin-stack-observer',
    risk: 'low',
    summary:
      'Observes the wrapProviderRunner stack and exposes it to operators (plugin_stack_status) and, optionally, to the LLM (system-prompt contributor).',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'dependency-vulnerability-gate',
    risk: 'high',
    summary:
      'PostToolUse hook that runs npm/pnpm audit after dependency installs and blocks or warns on vulnerabilities above a severity threshold',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'migration-planner',
    risk: 'low',
    summary:
      'Builds evidence-backed migration checklists with optional host-routed LLM risk analysis',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'semantic-search-indexer',
    risk: 'low',
    summary:
      'Builds an in-memory keyword index over project source files and answers ranked search queries',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'auto-i18n-extractor',
    risk: 'low',
    summary:
      'Detects hardcoded user-facing strings in UI source files and suggests translation keys',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'doc-sync-guard',
    risk: 'low',
    summary:
      'PostToolUse hook that tracks changed public source files and warns when README/docs edits omit them',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'api-compatibility-gate',
    risk: 'medium',
    summary:
      'PostToolUse hook that detects breaking API changes (removed exports) in entry-point files after writes or edits',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'performance-regression-gate',
    risk: 'medium',
    summary:
      'Compares benchmark results to detect performance regressions and reports metrics that increased beyond the configured threshold',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'test-flake-detector',
    risk: 'medium',
    summary: 'Runs a test command multiple times and reports tests that fail non-deterministically',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'schema-evolution-guard',
    risk: 'high',
    summary:
      'PostToolUse hook that guards database/API schema changes by detecting destructive patterns in schema files',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'license-audit-gate',
    risk: 'high',
    summary:
      'PostToolUse hook that audits dependency licenses after package-manager install/add commands and blocks disallowed licenses',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'accessibility-auditor',
    risk: 'medium',
    summary:
      'Audits .tsx/.jsx/.html/.vue files for common accessibility issues and reports findings after writes/edits',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'security-hotspot-scanner',
    risk: 'high',
    summary:
      'Scans source code for security anti-patterns and warns after writes/edits that introduce new hotspots',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'dead-code-detector',
    risk: 'low',
    summary:
      'Lightweight regex-based scan for exported identifiers that appear unused anywhere in the project',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'duplicate-code-detector',
    risk: 'low',
    summary:
      'Finds duplicated code blocks across source files using normalized-line fingerprinting',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'code-metrics',
    risk: 'low',
    summary:
      'Computes per-file line counts, function counts, and cyclomatic-complexity-like scores',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'refactor-suggester',
    risk: 'low',
    summary: 'Suggests refactoring opportunities using regex-based smell detection',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'test-generator',
    risk: 'low',
    summary:
      'Generates framework-correct test skeletons with optional host-routed LLM test authoring',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'release-notes-generator',
    risk: 'low',
    summary:
      'Generates traceable release notes from conventional commits with optional LLM polishing',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'smart-rename',
    risk: 'medium',
    summary: 'Whole-word identifier rename inside a single source file',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'feature-flag-tracker',
    risk: 'low',
    summary: 'Scans source files for feature-flag-like expressions and reports usages',
    defaultState: 'inactive',
    canDisable: true,
  },
  {
    name: 'interface-contract-guard',
    risk: 'medium',
    summary: 'Checks TypeScript interfaces for visible implementers and warns about contract drift',
    defaultState: 'inactive',
    canDisable: true,
  },
] as const;
