// Generated by scripts/generate-plugin-projections.mjs. Do not edit.
import type { PluginDetail } from './plugin-detail-types';
export const workflowPluginDetails: Record<string, PluginDetail> = {
  'workspace-health': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Inspects supplied workspace configuration evidence for broken package-manager, Node, and script contracts. Opt in through config.plugins; tools run only when invoked. Inspect package.json, tool output, or workspace configuration for health-contract failures. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
    tools: [
      {
        name: 'workspace_health_analyze',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect package.json, tool output, or workspace configuration for health-contract failures. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Project-relative file containing evidence to inspect.',
          },
          {
            name: 'content',
            type: 'string',
            description: 'Pasted evidence, such as a CI log or manifest text.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional model suggestions or a Jev next-check decision from finding metadata. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Master switch.',
      },
      {
        name: 'maxFindings',
        type: 'number',
        defaultValue: '40',
        description: 'Maximum reported findings per analysis.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "workspace-health",\n      "enabled": true\n    }\n  ]\n}',
  },
  'test-impact-analyzer': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Inspects diffs and test output for untested changes, focused-test exclusions, and skipped coverage evidence. Opt in through config.plugins; tools run only when invoked. Inspect a diff, changed-file list, or test output for test-impact signals. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
    tools: [
      {
        name: 'test_impact_analyze',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect a diff, changed-file list, or test output for test-impact signals. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Project-relative file containing evidence to inspect.',
          },
          {
            name: 'content',
            type: 'string',
            description: 'Pasted evidence, such as a CI log or manifest text.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional model suggestions or a Jev next-check decision from finding metadata. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Master switch.',
      },
      {
        name: 'maxFindings',
        type: 'number',
        defaultValue: '40',
        description: 'Maximum reported findings per analysis.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "test-impact-analyzer",\n      "enabled": true\n    }\n  ]\n}',
  },
  'ci-failure-triage': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Classifies supplied CI logs into actionable dependency, test, type-check, and infrastructure failure evidence. Opt in through config.plugins; tools run only when invoked. Inspect CI or command output and classify actionable failure signatures. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
    tools: [
      {
        name: 'ci_failure_triage',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect CI or command output and classify actionable failure signatures. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Project-relative file containing evidence to inspect.',
          },
          {
            name: 'content',
            type: 'string',
            description: 'Pasted evidence, such as a CI log or manifest text.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional model suggestions or a Jev next-check decision from finding metadata. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Master switch.',
      },
      {
        name: 'maxFindings',
        type: 'number',
        defaultValue: '40',
        description: 'Maximum reported findings per analysis.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "ci-failure-triage",\n      "enabled": true\n    }\n  ]\n}',
  },
  'env-contract-guard': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Inspects environment templates and runtime diagnostics for missing, placeholder, or accidentally exposed configuration contracts. Opt in through config.plugins; tools run only when invoked. Inspect an environment template or runtime diagnostic without submitting secret values. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
    tools: [
      {
        name: 'env_contract_analyze',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect an environment template or runtime diagnostic without submitting secret values. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Project-relative file containing evidence to inspect.',
          },
          {
            name: 'content',
            type: 'string',
            description: 'Pasted evidence, such as a CI log or manifest text.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional model suggestions or a Jev next-check decision from finding metadata. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Master switch.',
      },
      {
        name: 'maxFindings',
        type: 'number',
        defaultValue: '40',
        description: 'Maximum reported findings per analysis.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "env-contract-guard",\n      "enabled": true\n    }\n  ]\n}',
  },
  'dependency-drift-detector': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Inspects manifests and package-manager output for unpinned ranges, lockfile mismatch, and peer dependency drift. Opt in through config.plugins; tools run only when invoked. Inspect a package manifest, lockfile fragment, or package-manager output for dependency drift. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
    tools: [
      {
        name: 'dependency_drift_analyze',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect a package manifest, lockfile fragment, or package-manager output for dependency drift. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Project-relative file containing evidence to inspect.',
          },
          {
            name: 'content',
            type: 'string',
            description: 'Pasted evidence, such as a CI log or manifest text.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional model suggestions or a Jev next-check decision from finding metadata. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Master switch.',
      },
      {
        name: 'maxFindings',
        type: 'number',
        defaultValue: '40',
        description: 'Maximum reported findings per analysis.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "dependency-drift-detector",\n      "enabled": true\n    }\n  ]\n}',
  },
  'release-readiness': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Inspects supplied release-gate output for unmet validation, dirty-tree, publish, and version-alignment evidence. Opt in through config.plugins; tools run only when invoked. Inspect release-gate output, a changelog, or a version manifest for blocking readiness evidence. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
    tools: [
      {
        name: 'release_readiness_analyze',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect release-gate output, a changelog, or a version manifest for blocking readiness evidence. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Project-relative file containing evidence to inspect.',
          },
          {
            name: 'content',
            type: 'string',
            description: 'Pasted evidence, such as a CI log or manifest text.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional model suggestions or a Jev next-check decision from finding metadata. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Master switch.',
      },
      {
        name: 'maxFindings',
        type: 'number',
        defaultValue: '40',
        description: 'Maximum reported findings per analysis.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "release-readiness",\n      "enabled": true\n    }\n  ]\n}',
  },
  'bundle-budget-guard': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Inspects build and bundle reports for budget breaches, unexpectedly large assets, and sourcemap publication signals. Opt in through config.plugins; tools run only when invoked. Inspect a bundle report or build output for size-budget and artifact exposure evidence. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
    tools: [
      {
        name: 'bundle_budget_analyze',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect a bundle report or build output for size-budget and artifact exposure evidence. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Project-relative file containing evidence to inspect.',
          },
          {
            name: 'content',
            type: 'string',
            description: 'Pasted evidence, such as a CI log or manifest text.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional model suggestions or a Jev next-check decision from finding metadata. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Master switch.',
      },
      {
        name: 'maxFindings',
        type: 'number',
        defaultValue: '40',
        description: 'Maximum reported findings per analysis.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "bundle-budget-guard",\n      "enabled": true\n    }\n  ]\n}',
  },
  'public-api-auditor': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Inspects public entry-point evidence for undocumented exports, deprecated contracts, and accidental internal API exposure. Opt in through config.plugins; tools run only when invoked. Inspect a public entry point or API report for documentation and compatibility signals. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
    tools: [
      {
        name: 'public_api_analyze',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect a public entry point or API report for documentation and compatibility signals. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Project-relative file containing evidence to inspect.',
          },
          {
            name: 'content',
            type: 'string',
            description: 'Pasted evidence, such as a CI log or manifest text.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional model suggestions or a Jev next-check decision from finding metadata. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Master switch.',
      },
      {
        name: 'maxFindings',
        type: 'number',
        defaultValue: '40',
        description: 'Maximum reported findings per analysis.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "public-api-auditor",\n      "enabled": true\n    }\n  ]\n}',
  },
  'lockfile-consistency-guard': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Inspects lockfile and install evidence for mixed package managers, integrity failures, and reproducibility breaks. Opt in through config.plugins; tools run only when invoked. Inspect lockfile text or install output for reproducibility and consistency evidence. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
    tools: [
      {
        name: 'lockfile_consistency_analyze',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect lockfile text or install output for reproducibility and consistency evidence. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Project-relative file containing evidence to inspect.',
          },
          {
            name: 'content',
            type: 'string',
            description: 'Pasted evidence, such as a CI log or manifest text.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional model suggestions or a Jev next-check decision from finding metadata. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Master switch.',
      },
      {
        name: 'maxFindings',
        type: 'number',
        defaultValue: '40',
        description: 'Maximum reported findings per analysis.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "lockfile-consistency-guard",\n      "enabled": true\n    }\n  ]\n}',
  },
  'change-risk-classifier': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Inspects diffs or change descriptions for authentication, persistence, destructive-operation, and compatibility risk signals. Opt in through config.plugins; tools run only when invoked. Inspect a diff or change description and surface risk signals that merit targeted proof. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
    tools: [
      {
        name: 'change_risk_analyze',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect a diff or change description and surface risk signals that merit targeted proof. Returns only evidence found in the supplied file or pasted content; it does not run commands.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Project-relative file containing evidence to inspect.',
          },
          {
            name: 'content',
            type: 'string',
            description: 'Pasted evidence, such as a CI log or manifest text.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional model suggestions or a Jev next-check decision from finding metadata. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Master switch.',
      },
      {
        name: 'maxFindings',
        type: 'number',
        defaultValue: '40',
        description: 'Maximum reported findings per analysis.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "change-risk-classifier",\n      "enabled": true\n    }\n  ]\n}',
  },
  'bug-reproducer': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Runs a supplied regression command twice against fingerprinted files and distinguishes a reproducible failure from instability or infrastructure errors. Opt in through config.plugins; tools run only when invoked. Run an explicit regression command twice. expectedOutput is a literal failure marker required to attribute the failure to the reported bug. Returns a portable Node test recipe and file fingerprints.',
    tools: [
      {
        name: 'bug_reproduce',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Run an explicit regression command twice. expectedOutput is a literal failure marker required to attribute the failure to the reported bug. Returns a portable Node test recipe and file fingerprints.',
        params: [
          {
            name: 'command',
            type: 'object',
            description: 'Required.',
          },
          {
            name: 'files',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'expectedOutput',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional advice only; model output cannot change deterministic results. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "bug-reproducer",\n      "enabled": true\n    }\n  ]\n}',
  },
  'verification-ledger': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Records executed checks with source fingerprints and invalidates their evidence when relevant files change within the host session. Opt in through config.plugins; tools run only when invoked. Execute a check and record its result against the exact supplied source files. Evidence is session-local; include all inputs influencing the check. Recompute source fingerprints for every recorded check; missing or modified files invalidate previous success.',
    tools: [
      {
        name: 'verification_record',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Execute a check and record its result against the exact supplied source files. Evidence is session-local; include all inputs influencing the check.',
        params: [
          {
            name: 'command',
            type: 'object',
            description: 'Required.',
          },
          {
            name: 'files',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'label',
            type: 'string',
            description: 'Required.',
          },
        ],
      },
      {
        name: 'verification_status',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Recompute source fingerprints for every recorded check; missing or modified files invalidate previous success.',
        params: [],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "verification-ledger",\n      "enabled": true\n    }\n  ]\n}',
  },
  'acceptance-verifier': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Executes explicit acceptance criteria and maps each requirement to a command result and source fingerprint, preserving missing and stale evidence. Opt in through config.plugins; tools run only when invoked. Verify each named criterion with its supplied command and files. Criteria without commands stay unverified; all must pass on unchanged sources.',
    tools: [
      {
        name: 'acceptance_verify',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Verify each named criterion with its supplied command and files. Criteria without commands stay unverified; all must pass on unchanged sources.',
        params: [
          {
            name: 'criteria',
            type: 'array',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "acceptance-verifier",\n      "enabled": true\n    }\n  ]\n}',
  },
  'runtime-trace-explorer': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Reconstructs parent-child runtime spans from a local trace export and identifies broken ancestry, failed spans and missing expected layers. Opt in through config.plugins; tools run only when invoked. Read JSON {spans:[{id,parentId?,traceId,layer,startMs,endMs,status}]} and inspect one trace. Optional layers declares required UI/API/service/storage stages.',
    tools: [
      {
        name: 'runtime_trace_explore',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Read JSON {spans:[{id,parentId?,traceId,layer,startMs,endMs,status}]} and inspect one trace. Optional layers declares required UI/API/service/storage stages.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'traceId',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'layers',
            type: 'array',
            description: 'Optional.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "runtime-trace-explorer",\n      "enabled": true\n    }\n  ]\n}',
  },
  'workspace-recipe-runner': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Discovers explicit package scripts and their package-manager and runtime prerequisites, then runs a selected structured command. Opt in through config.plugins; tools run only when invoked. Read a package.json and list its scripts, working directory, declared package manager, engines and required workspace dependency builds. Execute a reviewed structured recipe with project-contained cwd, cancellation and timeout.',
    tools: [
      {
        name: 'workspace_recipes',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Read a package.json and list its scripts, working directory, declared package manager, engines and required workspace dependency builds.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Required.',
          },
        ],
      },
      {
        name: 'workspace_recipe_run',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Execute a reviewed structured recipe with project-contained cwd, cancellation and timeout.',
        params: [
          {
            name: 'command',
            type: 'object',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "workspace-recipe-runner",\n      "enabled": true\n    }\n  ]\n}',
  },
  'architecture-boundary-checker': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Builds a literal source import graph, reports dependency cycles, and checks explicitly forbidden directory boundaries. Opt in through config.plugins; tools run only when invoked. Inspect imports in the supplied files. forbidden contains {from,to} directory prefixes; unresolved external/alias imports remain visible.',
    tools: [
      {
        name: 'architecture_boundaries',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Inspect imports in the supplied files. forbidden contains {from,to} directory prefixes; unresolved external/alias imports remain visible.',
        params: [
          {
            name: 'files',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'forbidden',
            type: 'array',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "architecture-boundary-checker",\n      "enabled": true\n    }\n  ]\n}',
  },
  'monorepo-change-planner': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Computes transitive workspace consumers and dependency-first validation order from explicit package manifests and changed paths. Opt in through config.plugins; tools run only when invoked. Supply workspace package.json paths and changed files. Returns impacted packages, dependency-first build/test recipes, cycles and unknown changes.',
    tools: [
      {
        name: 'monorepo_change_plan',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Supply workspace package.json paths and changed files. Returns impacted packages, dependency-first build/test recipes, cycles and unknown changes.',
        params: [
          {
            name: 'manifests',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'changedFiles',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'review',
            type: 'string',
            description:
              'Optional advice only; model output cannot change deterministic results. Default none.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "monorepo-change-planner",\n      "enabled": true\n    }\n  ]\n}',
  },
  'config-migration-assistant': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Previews explicit JSON configuration key renames and defaults while preserving custom values and refusing destination conflicts. Opt in through config.plugins; tools run only when invoked. Return migrated JSON without writing. renames is [{from,to}] for top-level keys; defaults fill only absent keys. Conflicting destinations reject the migration.',
    tools: [
      {
        name: 'config_migration_preview',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Return migrated JSON without writing. renames is [{from,to}] for top-level keys; defaults fill only absent keys. Conflicting destinations reject the migration.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'renames',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'defaults',
            type: 'object',
            description: 'Optional.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "config-migration-assistant",\n      "enabled": true\n    }\n  ]\n}',
  },
  'feature-flag-lifecycle': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Maps declared feature flags to literal source references and reports expired flags and definitions without visible consumers. Opt in through config.plugins; tools run only when invoked. Supply flags [{name,expiresAt?,owner?}] and source files. Reports exact literal-token references, expiry and retirement review candidates; dynamic flag construction is outside scope.',
    tools: [
      {
        name: 'feature_flag_inventory',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Supply flags [{name,expiresAt?,owner?}] and source files. Reports exact literal-token references, expiry and retirement review candidates; dynamic flag construction is outside scope.',
        params: [
          {
            name: 'flags',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'files',
            type: 'array',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "feature-flag-lifecycle",\n      "enabled": true\n    }\n  ]\n}',
  },
  'generated-artifact-tracker': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Tracks source and generated-output fingerprints for declared generators and reports which artifacts need regeneration after changes. Opt in through config.plugins; tools run only when invoked. action=capture records a caller-approved source/output baseline in this host session. action=check compares it. rules: [{id,inputs,outputs,command}]. Capture does not prove a generator was run.',
    tools: [
      {
        name: 'generated_artifacts',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'action=capture records a caller-approved source/output baseline in this host session. action=check compares it. rules: [{id,inputs,outputs,command}]. Capture does not prove a generator was run.',
        params: [
          {
            name: 'action',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'rules',
            type: 'array',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "generated-artifact-tracker",\n      "enabled": true\n    }\n  ]\n}',
  },
  'api-consumer-replay': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Replays explicit consumer HTTP fixtures against a loopback API and compares status and selected JSON fields without following redirects. Opt in through config.plugins; tools run only when invoked. Replay cases [{path,method?,body?,expectedStatus,expectedJson?}] against baseUrl on 127.0.0.1/[::1]. Mutating methods require the normal tool approval.',
    tools: [
      {
        name: 'api_consumer_replay',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Replay cases [{path,method?,body?,expectedStatus,expectedJson?}] against baseUrl on 127.0.0.1/[::1]. Mutating methods require the normal tool approval.',
        params: [
          {
            name: 'baseUrl',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'cases',
            type: 'array',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "api-consumer-replay",\n      "enabled": true\n    }\n  ]\n}',
  },
  'migration-rehearsal': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Rehearses SQLite up/down migrations in a fresh in-memory database and compares schema and data snapshots before and after rollback. Opt in through config.plugins; tools run only when invoked. Execute seed, up and optional down SQL files against an in-memory SQLite database in a child process. Requires Node with node:sqlite. SQL ATTACH and extension loading are not permitted.',
    tools: [
      {
        name: 'migration_rehearse',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Execute seed, up and optional down SQL files against an in-memory SQLite database in a child process. Requires Node with node:sqlite. SQL ATTACH and extension loading are not permitted.',
        params: [
          {
            name: 'seed',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'up',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'down',
            type: 'string',
            description: 'Optional.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "migration-rehearsal",\n      "enabled": true\n    }\n  ]\n}',
  },
  'failure-injection-lab': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Runs a caller-supplied recovery test against a temporary loopback endpoint injecting HTTP 429, malformed JSON, disconnects or delayed responses. Opt in through config.plugins; tools run only when invoked. Run command with {faultUrl} in an argv element replaced by the temporary endpoint. scenario: rate-limit, malformed-json, disconnect, delay. The test must assert recovery itself.',
    tools: [
      {
        name: 'failure_inject',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Run command with {faultUrl} in an argv element replaced by the temporary endpoint. scenario: rate-limit, malformed-json, disconnect, delay. The test must assert recovery itself.',
        params: [
          {
            name: 'command',
            type: 'object',
            description: 'Required.',
          },
          {
            name: 'scenario',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'delayMs',
            type: 'integer',
            description: 'Optional.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "failure-injection-lab",\n      "enabled": true\n    }\n  ]\n}',
  },
  'concurrency-scenario-tester': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Issues synchronized loopback HTTP requests and verifies an explicit allowed-success count plus an optional final-state JSON invariant. Opt in through config.plugins; tools run only when invoked. Send count identical requests concurrently. expectedSuccesses is required; optional invariant {url,expectedJson} checks final state. Use only a disposable local test service.',
    tools: [
      {
        name: 'concurrency_test',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Send count identical requests concurrently. expectedSuccesses is required; optional invariant {url,expectedJson} checks final state. Use only a disposable local test service.',
        params: [
          {
            name: 'url',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'method',
            type: 'string',
            description: 'Optional.',
          },
          {
            name: 'body',
            type: 'any',
            description: 'Optional.',
          },
          {
            name: 'count',
            type: 'integer',
            description: 'Required.',
          },
          {
            name: 'expectedSuccesses',
            type: 'integer',
            description: 'Required.',
          },
          {
            name: 'invariant',
            type: 'object',
            description: 'Optional.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "concurrency-scenario-tester",\n      "enabled": true\n    }\n  ]\n}',
  },
  'resource-lifecycle-inspector': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Runs a JavaScript lifecycle fixture repeatedly in a child process and compares observable active resource counts after each cleanup against its baseline. Opt in through config.plugins; tools run only when invoked. Import a local .mjs fixture exporting async start() and stop(handle). Runs cycles and reports retained observable resources after settling; fixture code executes with your user permissions.',
    tools: [
      {
        name: 'resource_lifecycle_inspect',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Import a local .mjs fixture exporting async start() and stop(handle). Runs cycles and reports retained observable resources after settling; fixture code executes with your user permissions.',
        params: [
          {
            name: 'fixture',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'cycles',
            type: 'integer',
            description: 'Optional.',
          },
          {
            name: 'settleMs',
            type: 'integer',
            description: 'Optional.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "resource-lifecycle-inspector",\n      "enabled": true\n    }\n  ]\n}',
  },
  'visual-regression-reviewer': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Compares decoded PNG screenshot pixels and reports changed-pixel ratios and a bounding rectangle with explicit tolerance. Opt in through config.plugins; tools run only when invoked. Compare baseline and current 8-bit RGB/RGBA PNGs. tolerance is per-channel 0..255; maxChangedPixels is the allowed pixel count. Size changes always fail.',
    tools: [
      {
        name: 'visual_regression_compare',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Compare baseline and current 8-bit RGB/RGBA PNGs. tolerance is per-channel 0..255; maxChangedPixels is the allowed pixel count. Size changes always fail.',
        params: [
          {
            name: 'baseline',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'current',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'tolerance',
            type: 'integer',
            description: 'Optional.',
          },
          {
            name: 'maxChangedPixels',
            type: 'integer',
            description: 'Optional.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "visual-regression-reviewer",\n      "enabled": true\n    }\n  ]\n}',
  },
  'responsive-journey-tester': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Runs explicit Playwright browser journeys at selected viewport sizes and checks required controls for visibility, reachability and horizontal overflow. Opt in through config.plugins; tools run only when invoked. Requires locally installed playwright and Chromium. Navigate a loopback URL, run steps [{action:click|fill|press,selector,value?}], then check selectors at every viewport [{width,height}].',
    tools: [
      {
        name: 'responsive_journey_test',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Requires locally installed playwright and Chromium. Navigate a loopback URL, run steps [{action:click|fill|press,selector,value?}], then check selectors at every viewport [{width,height}].',
        params: [
          {
            name: 'url',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'viewports',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'steps',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'selectors',
            type: 'array',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "responsive-journey-tester",\n      "enabled": true\n    }\n  ]\n}',
  },
  'localization-completeness': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Compares nested JSON locale keys, empty translations and interpolation variables across languages, including explicitly keyed plural variants. Opt in through config.plugins; tools run only when invoked. Compare base JSON locale with locales mapping language names to project file paths. Checks missing/extra keys, empty strings and placeholder sets; does not parse full ICU grammar.',
    tools: [
      {
        name: 'localization_compare',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Compare base JSON locale with locales mapping language names to project file paths. Checks missing/extra keys, empty strings and placeholder sets; does not parse full ICU grammar.',
        params: [
          {
            name: 'base',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'locales',
            type: 'object',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "localization-completeness",\n      "enabled": true\n    }\n  ]\n}',
  },
  'executable-documentation': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Executes explicitly marked JavaScript documentation examples in Node and records their actual exit status and source location. Opt in through config.plugins; tools run only when invoked. Run only fenced blocks beginning ```js verify or ```javascript verify from the selected Markdown file. Executes with Node ESM in the project directory; examples should contain assertions.',
    tools: [
      {
        name: 'documentation_verify',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Run only fenced blocks beginning ```js verify or ```javascript verify from the selected Markdown file. Executes with Node ESM in the project directory; examples should contain assertions.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "executable-documentation",\n      "enabled": true\n    }\n  ]\n}',
  },
  'dependency-upgrade-sandbox': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Copies selected fixture files to a temporary directory, changes one npm dependency, installs without lifecycle scripts and runs explicit validation commands. Opt in through config.plugins; tools run only when invoked. For standalone npm packages: copy files (must include package.json), update dependency to an exact version, npm install --ignore-scripts, then run checks. Original files stay unchanged; temporary files are removed afterward. This is directory isolation, not an OS security sandbox.',
    tools: [
      {
        name: 'dependency_upgrade_try',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'For standalone npm packages: copy files (must include package.json), update dependency to an exact version, npm install --ignore-scripts, then run checks. Original files stay unchanged; temporary files are removed afterward. This is directory isolation, not an OS security sandbox.',
        params: [
          {
            name: 'files',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'dependency',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'version',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'registry',
            type: 'string',
            description:
              'Optional HTTP(S) npm registry without embedded credentials; useful for private/offline test registries.',
          },
          {
            name: 'checks',
            type: 'array',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "dependency-upgrade-sandbox",\n      "enabled": true\n    }\n  ]\n}',
  },
  'developer-environment-doctor': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Probes the active Node runtime, declared package-manager launcher and dependency-install presence using the project package manifest. Opt in through config.plugins; tools run only when invoked. Probe Node and the declared npm/pnpm/yarn/bun launcher with --version; compare exact packageManager pin and detect a missing node_modules. Engine ranges are reported, not guessed.',
    tools: [
      {
        name: 'developer_environment_check',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Probe Node and the declared npm/pnpm/yarn/bun launcher with --version; compare exact packageManager pin and detect a missing node_modules. Engine ranges are reported, not guessed.',
        params: [
          {
            name: 'manifest',
            type: 'string',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "developer-environment-doctor",\n      "enabled": true\n    }\n  ]\n}',
  },
  'service-topology-inspector': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Probes declared loopback service health endpoints, maps dependency failures and reports missing services and topology cycles. Opt in through config.plugins; tools run only when invoked. Supply services [{name,url,dependsOn?}]. Probe each health URL once and return unhealthy dependencies and cycles. Does not start or stop services.',
    tools: [
      {
        name: 'service_topology_inspect',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Supply services [{name,url,dependsOn?}]. Probe each health URL once and return unhealthy dependencies and cycles. Does not start or stop services.',
        params: [
          {
            name: 'services',
            type: 'array',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "service-topology-inspector",\n      "enabled": true\n    }\n  ]\n}',
  },
  'decision-journal': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Appends explicit architectural decisions and rationales to a project JSONL journal and retrieves decisions linked to changed files. Opt in through config.plugins; tools run only when invoked. Append {title,rationale,files} to an explicit project-contained JSONL journal. Each record has an id and timestamp. Does not inject decisions into prompts automatically. Read a JSONL decision journal; return decisions associated with supplied paths, along with explicit supersession links.',
    tools: [
      {
        name: 'decision_record',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Append {title,rationale,files} to an explicit project-contained JSONL journal. Each record has an id and timestamp. Does not inject decisions into prompts automatically.',
        params: [
          {
            name: 'journal',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'title',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'rationale',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'files',
            type: 'array',
            description: 'Required.',
          },
          {
            name: 'supersedes',
            type: 'string',
            description: 'Optional.',
          },
        ],
      },
      {
        name: 'decision_lookup',
        category: 'Diagnostics',
        permission: 'auto',
        mutating: false,
        summary:
          'Read a JSONL decision journal; return decisions associated with supplied paths, along with explicit supersession links.',
        params: [
          {
            name: 'journal',
            type: 'string',
            description: 'Required.',
          },
          {
            name: 'files',
            type: 'array',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "decision-journal",\n      "enabled": true\n    }\n  ]\n}',
  },
  'plugin-workbench': {
    version: '0.1.0',
    apiVersion: '^0.1.10',
    longDescription:
      'Loads a built plugin in a bounded child-process harness and measures duplicate tool registration, hook cleanup and setup/teardown lifecycle behavior. Opt in through config.plugins; tools run only when invoked. Load a local built ESM plugin with a default export into a mocked host. Setup twice then teardown, report duplicate registrations and remaining hooks. Plugin code executes with user permissions; this is not an OS sandbox.',
    tools: [
      {
        name: 'plugin_workbench_run',
        category: 'Diagnostics',
        permission: 'confirm',
        mutating: true,
        summary:
          'Load a local built ESM plugin with a default export into a mocked host. Setup twice then teardown, report duplicate registrations and remaining hooks. Plugin code executes with user permissions; this is not an OS sandbox.',
        params: [
          {
            name: 'path',
            type: 'string',
            description: 'Required.',
          },
        ],
      },
    ],
    configOptions: [
      {
        name: 'enabled',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Enable this workflow after the plugin is loaded.',
      },
    ],
    hooks: [],
    example:
      '{\n  "plugins": [\n    {\n      "name": "plugin-workbench",\n      "enabled": true\n    }\n  ]\n}',
  },
};
