/**
 * Default allowlist of command NAMES the `exec` tool may run.
 *
 * Extracted from exec.ts for auditability. Only the command name is gated
 * (per-arg safety is the BLOCKED_ARG_PATTERNS denylist in exec.ts + the
 * per-call `confirm` permission). A prior version mapped each command to an
 * allowed-args array, but those arrays were never enforced (dead code) — a
 * plain Set is the honest shape.
 *
 * Extend/trim at runtime via `configureExecPolicy()` (wired from
 * `config.tools.exec.{allow,deny}` at boot). `allow` is trusted-config-only;
 * see the security note on ExecToolConfig.
 */
export const DEFAULT_ALLOWED_COMMANDS: ReadonlySet<string> = new Set([
  // JS / TS toolchain
  'node',
  'npm',
  'pnpm',
  'yarn',
  'npx',
  'bun',
  'deno',
  'corepack',
  'tsc',
  'tsx',
  'ts-node',
  'vite',
  'vitest',
  'jest',
  'biome',
  'eslint',
  'prettier',
  'turbo',
  'nx',
  'webpack',
  'rollup',
  'parcel',
  'next',
  'astro',
  'playwright',
  'cypress',
  // version control
  'git',
  // Rust
  'cargo',
  'rustc',
  // Go
  'go',
  // Python
  'python',
  'python3',
  'pip',
  'pip3',
  'pytest',
  'ruff',
  'mypy',
  'uv',
  'uvx',
  'poetry',
  'hatch',
  'tox',
  // Ruby
  'ruby',
  'gem',
  'bundle',
  // PHP
  'php',
  'composer',
  'phpunit',
  // JVM
  'java',
  'javac',
  'mvn',
  'gradle',
  'gradlew',
  // .NET
  'dotnet',
  // C / C++ / native build
  'make',
  'cmake',
  'ninja',
  'clang',
  'clang-cl',
  'gcc',
  'g++',
  'link',
  'msbuild',
  // containers / orchestration
  'docker',
  'podman',
  'kubectl',
  // network fetch tools. Per-arg safety is NOT enforced by BLOCKED_ARG_PATTERNS
  // (no curl/wget entries) — the real boundary is the per-call `confirm`
  // permission gate (exec.ts permission:'confirm', subjectKey:'command'),
  // the `pipe-to-shell` danger rule, and the kill guard. The allowlist is a
  // guidance layer, not a security boundary on its own.
  'curl',
  'wget',
  // common POSIX file/text utilities
  'pwd',
  'ls',
  'cat',
  'head',
  'tail',
  'wc',
  'grep',
  'rg',
  'find',
  'echo',
  'sort',
  'uniq',
  'sed',
  'awk',
  'mkdir',
  'cp',
  'mv',
  'rm',
  'touch',
  'tar',
  // Windows-native tooling (win32). All non-destructive binaries; per-arg
  // safety is still enforced by BLOCKED_ARG_PATTERNS + the destructive-ops
  // gate in bash-kill-guard.ts. `gh` is included even though it lives at
  // "C:\Program Files\GitHub CLI\gh.exe" — resolveWin32Command handles the
  // space in the path.
  'gh',
  'where',
  'tasklist',
  'systeminfo',
  'wmic',
  'sc',
  'netstat',
  'ipconfig',
  'nslookup',
  'tracert',
  'pathping',
  // Windows shell interpreters. Without these, `exec` cannot run cmd builtins
  // (`dir`, `type`, `copy`, …) or any PowerShell cmdlet on Windows — a major
  // gap since those are the platform's primary shells. Arbitrary execution
  // through `cmd /c …` / `powershell -c …` is NOT a new hole: the permission
  // policy reconstructs the full command line (shellCommandLineFromInput) and
  // still runs it through the YOLO destructive classifier, so a genuinely
  // destructive `cmd /c del /s /q C:\…` continues to require confirmation.
  'cmd',
  'cmd.exe',
  'powershell',
  'powershell.exe',
  'pwsh',
  'pwsh.exe',
  // [core] Extended default allowlist (added 4b3d18d1 + this commit). Broadly
  // used dev binaries — NOT all non-destructive: this section contains
  // process/system tools (kill, chown, mount, userdel), network scanners
  // (nmap, masscan, zmap, nuclei), and launchers (env, perl, timeout, tmux).
  // The real safety boundary for these is the per-call `confirm` permission
  // gate (exec.ts permission:'confirm', subjectKey:'command' renders the full
  // invocation) plus the danger rules in _danger-detect.ts. Per-arg hard-deny
  // is still enforced by BLOCKED_ARG_PATTERNS + bash-kill-guard.ts, but only
  // for the commands that have entries there (git, find, rm).
  // --- Archives & compression ---
  '7z',
  '7za',
  'bzip2',
  'gzip',
  'xz',
  'unzip',
  'zip',
  'gtar',
  'bsdtar',
  'star',
  'pax',
  'cpio',
  // --- Android / mobile dev ---
  'adb',
  'fastboot',
  'sdkmanager',
  // --- DevOps / config mgmt ---
  'ansible',
  'ansible-playbook',
  'ansible-vault',
  'ansible-lint',
  'ansible-galaxy',
  'molecule',
  // --- Cloud CLIs ---
  'aws',
  'aws-vault',
  'awslocal',
  'az',
  'azcopy',
  'gcloud',
  'gsutil',
  'doctl',
  'linode-cli',
  // --- Native / C / C++ / linker tools ---
  'clang++',
  'clang-format',
  'clang-tidy',
  'clangd',
  'lld',
  'lldb',
  'ctest',
  'gmake',
  'meson',
  'conan',
  'vcpkg',
  'cl',
  'rc',
  'mt',
  'dumpbin',
  'dotnet-format',
  // --- Image / media / binary tools ---
  'convert',
  'ffmpeg',
  'ffprobe',
  'magick',
  'gs',
  'exiftool',
  // --- HTTP / fetch ---
  'wget2',
  'aria2c',
  'axel',
  'httpie',
  'hey',
  'ab',
  'wrk',
  'http',
  // --- Diff / patch / merge ---
  'diff',
  'diff3',
  'patch',
  'meld',
  'kdiff3',
  'kompare',
  // --- Encoding / file inspection ---
  'dos2unix',
  'unix2dos',
  'iconv',
  'file',
  'stat',
  'xxd',
  'hexdump',
  'od',
  'base64',
  // --- SSH / crypto / signing ---
  'ssh',
  'ssh-add',
  'ssh-keygen',
  'ssh-keyscan',
  'scp',
  'sftp',
  'rsync',
  'gpg',
  'gpg2',
  'gpg-agent',
  'openssl',
  'step',
  'keytool',
  // --- Search ---
  'egrep',
  'fgrep',
  'ag',
  'ack',
  'sift',
  'ugrep',
  'fd',
  'fdfind',
  'jq',
  'yq',
  'xq',
  'fx',
  'gron',
  // --- K8s / container ecosystem ---
  'kubectl.exe',
  'kubeadm',
  'kubelet',
  'helm',
  'k9s',
  'kustomize',
  'skaffold',
  'tilt',
  'minikube',
  'kind',
  'k3d',
  'k3s',
  'docker-compose',
  'buildah',
  'skopeo',
  'nerdctl',
  'ctr',
  'ctr.exe',
  // --- Databases ---
  'sqlite3',
  'sqlite',
  'psql',
  'pg_dump',
  'pg_restore',
  'mysql',
  'mysqladmin',
  'mysqldump',
  'mariadb',
  'mariadb-dump',
  'redis-cli',
  'redis-server',
  'memcached',
  'etcdctl',
  'consul',
  'vault',
  'nomad',
  'mongosh',
  'mongo',
  'mongoexport',
  'mongoimport',
  'mongodump',
  'mongorestore',
  // --- Windows extended (read-mostly ops) ---
  'taskkill',
  'gpupdate',
  'gpresult',
  'hostname',
  'whoami',
  'who',
  'net',
  'net1',
  // --- VCS ecosystem ---
  'glab',
  'hub',
  'tea',
  'git-lfs',
  'tig',
  'lazygit',
  // --- POSIX text utilities (extended) ---
  'gawk',
  'tr',
  'cut',
  'paste',
  'join',
  'comm',
  'expand',
  'unexpand',
  'fold',
  'fmt',
  'nl',
  'pr',
  'column',
  'tsort',
  'tty',
  'ul',
  'units',
  'factor',
  'seq',
  'shuf',
  'look',
  'yes',
  'true',
  'false',
  'test',
  '[',
  'printf',
  'env',
  'tree',
  'locate',
  'which',
  'whereis',
  // NOTE: shell builtins with no standalone binary (type, hash, pushd,
  // popd, dirs, history, fc, jobs, bg, fg, wait, ulimit, umask, trap,
  // exit, return, source, ., alias, unalias, set, unset, export, readonly,
  // typeset, declare, local, eval, exec) are intentionally excluded —
  // spawn() would fail with ENOENT on every platform because they only
  // exist inside a shell process. Use the `bash` tool for builtins.
  'nice',
  'nohup',
  'timeout',
  'time',
  // --- Process / system inspection ---
  'htop',
  'top',
  'atop',
  'glances',
  'iotop',
  'nethogs',
  'iftop',
  'lsof',
  'strace',
  'ltrace',
  'sysstat',
  'vmstat',
  'iostat',
  'mpstat',
  'sar',
  'free',
  'df',
  'du',
  'mount',
  'umount',
  'lsblk',
  'blkid',
  'kill',
  'killall',
  'pkill',
  'pgrep',
  'pidof',
  'ps',
  'ps.exe',
  // --- Network inspection ---
  'ip',
  'ss',
  'route',
  'arp',
  'arping',
  'ping',
  'ping6',
  'hping3',
  'mtr',
  'tracepath',
  'tcpdump',
  'nmap',
  'netcat',
  'nc',
  'ncat',
  'socat',
  // --- Sync / backup ---
  'rclone',
  'restic',
  'borg',
  'duplicati',
  'duplicacy',
  'syncthing',
  'syncthing-cli',
  // --- Permissions / users / ACLs (POSIX) ---
  'useradd',
  'userdel',
  'usermod',
  'groupadd',
  'groupdel',
  'groupmod',
  'chown',
  'chmod',
  'chgrp',
  'getfacl',
  'setfacl',
  'setcap',
  'getcap',
  // --- Crypto / cert mgmt (extended) ---
  'certbot',
  'mkcert',
  'jarsigner',
  // --- Editors ---
  'subl',
  'code',
  'code-insiders',
  'cursor',
  'atom',
  'nano',
  'vim',
  'nvim',
  'vi',
  'emacs',
  'helix',
  'hx',
  'micro',
  'jed',
  'ed',
  'ex',
  'mg',
  // --- Terminal multiplexers ---
  'asciinema',
  'script',
  'scriptreplay',
  'expect',
  'screen',
  'tmux',
  'byobu',
  'dtach',
  'abduco',
  // --- Calculators / REPLs / scientific ---
  'bc',
  'dc',
  'calc',
  'qalc',
  'genius',
  'octave',
  'R',
  'Rscript',
  'julia',
  'irb',
  'pry',
  'ghci',
  'stack',
  'cabal',
  'ghc',
  // --- PHP / Lua / Perl / Ruby ecosystem (extended) ---
  'php8',
  'php7',
  'phpcs',
  'phpcbf',
  'phpmd',
  'phpstan',
  'psalm',
  'lua',
  'lua5.1',
  'lua5.2',
  'lua5.3',
  'lua5.4',
  'luarocks',
  'perl',
  'cpan',
  'prove',
  'plackup',
  'rake',
  'rspec',
  'jekyll',
  'node-gyp',
  'node-pre-gyp',
  // --- JS / TS toolchain (extended) ---
  'electron',
  'electron-builder',
  'electron-forge',
  'vite-preview',
  'swc',
  'swc-cli',
  'swcpack',
  'mocha',
  'chai',
  'jasmine',
  'puppeteer',
  'lighthouse',
  // --- Linters / formatters (extended) ---
  'tslint',
  'stylelint',
  'htmlhint',
  'jshint',
  'jslint',
  'jscs',
  // --- Document conversion ---
  'pandoc',
  'weasyprint',
  'wkhtmltopdf',
  'wkhtmltoimage',
  'prince',
  'mdp',
  'markdown',
  'multimarkdown',
  'cmark',
  'cmark-gfm',
  // --- Office / spreadsheet ---
  'soffice',
  'libreoffice',
  'unoconv',
  'abiword',
  'gnumeric',
  // --- Spell / grammar ---
  'aspell',
  'hunspell',
  'enchant',
  'languagetool',
  // --- Source-highlight / diff tools ---
  'delta',
  'bat',
  'ccat',
  'hl',
  'highlight',
  'source-highlight',
  'ansifilter',
  // --- Job schedulers ---
  'pueue',
  'task-spooler',
  'ts',
  'at',
  'atd',
  'anacron',
  'fcron',
  'cronie',
  'systemd-run',
  'systemd-cat',
  // --- Plotting / visualization ---
  'gnuplot',
  'gnuplot-nox',
  'veusz',
  'scidavis',
  'grace',
  'xmgrace',
  'labplot',
  // --- Security / recon (network + web) ---
  'masscan',
  'zmap',
  'rustscan',
  'amass',
  'subfinder',
  'httpx',
  'nuclei',
  'naabu',
  'katana',
  'dnsx',
  'assetfinder',
  'findomain',
  'gau',
  'waybackurls',
  'httprobe',
  'meg',
  'subjack',
  'sublert',
  'chaos',
]);
