import type { JSONSchema } from '@wrongstack/core/types';

export const KANBAN_TOOL_DESCRIPTION =
  'Manage and audit project-scoped multi-kanban boards through the shared IPC Kanban server and its SQLite store. Managed cards enforce fully specified details and adjacent Backlog → Todo → Running → Review → Done transitions with persistent comments and evidence. Contract Map actions are optional advisory metadata unless an operator explicitly enabled strict enforcement. Use verify_completion to validate executable success criteria before Done.';

export const KANBAN_TOOL_USAGE_HINT =
  'Use this for durable project kanban state. Read workbench when orienting across boards; it returns bounded Now, Next, Blocked, Review lanes and operational alerts. Before coding mutation, create a fully detailed card on a managed board with executable acceptance criteria, then call start_task. The runtime blocks product mutations until start_task binds a ready Running card. Do not create, inspect, repair, or enable a Contract Map during ordinary work; every map mode stays off the execution and completion path. Worker completion enters Review; Done requires passed acceptance criteria and review evidence. Surface existing strict-map findings for operator review without stopping work to repair them.';

export const KANBAN_INPUT_SCHEMA: JSONSchema = {
  type: 'object',
  properties: {
    action: {
      type: 'string',
      enum: [
        'list_boards',
        'get_board',
        'create_board',
        'duplicate_board',
        'update_board',
        'adopt_managed_lifecycle',
        'delete_board',
        'generate_board',
        'export_markdown',
        'export_task_graph',
        'sync_task_graph',
        'create_from_graph',
        'import_session_tasks',
        'search_tasks',
        'ready_tasks',
        'snapshot',
        'workbench',
        'add_column',
        'update_column',
        'delete_column',
        'add_task',
        'split_task',
        'merge_tasks',
        'copy_task',
        'transfer_task',
        'get_task',
        'start_task',
        'update_task',
        'transition_task',
        'repair_managed_projection',
        'move_task',
        'delete_task',
        'set_chain',
        'get_chain',
        'get_contract_graph',
        'configure_contract_graph',
        'upsert_contract_node',
        'link_contract_nodes',
        'remove_contract_node',
        'remove_contract_edge',
        'evaluate_contract_graph',
        'claim_task',
        'release_task',
        'assign_task',
        'mark_assignment',
        'heartbeat_assignment',
        'recover_stale',
        'events',
        'queue_health',
        'add_dependency',
        'add_goal_metric',
        'update_goal_metric',
        'add_check',
        'update_check',
        'add_note',
        'add_link',
        'verify_completion',
        'split_atomic',
        'assess_atomicity',
        'propose_decomposition',
      ],
    },
    boardId: { type: 'string' },
    taskId: { type: 'string' },
    taskIds: { type: 'array', items: { type: 'string' } },
    chainId: { type: 'string' },
    contractNodeId: { type: 'string' },
    contractNodeKind: {
      type: 'string',
      enum: ['objective', 'guardrail', 'risk', 'component', 'artifact', 'verification'],
    },
    contractNodeState: {
      type: 'string',
      enum: ['unknown', 'active', 'satisfied', 'violated', 'resolved'],
    },
    contractEnforcement: {
      type: 'string',
      enum: ['blocking', 'advisory', 'informational'],
    },
    contractGraphEnforcement: { type: 'string', enum: ['off', 'advisory', 'strict'] },
    contractEdgeId: { type: 'string' },
    contractEdgeType: {
      type: 'string',
      enum: [
        'targets',
        'affects',
        'must_preserve',
        'exposes',
        'verified_by',
        'conflicts_with',
        'derived_from',
        'relates_to',
      ],
    },
    fromNodeId: { type: 'string' },
    toNodeId: { type: 'string' },
    contractRationale: { type: 'string' },
    baseline: { oneOf: [{ type: 'string' }, { type: 'number' }] },
    threshold: { oneOf: [{ type: 'string' }, { type: 'number' }] },
    columnId: { type: 'string' },
    targetBoardId: { type: 'string' },
    targetColumnId: { type: 'string' },
    title: { type: 'string' },
    description: { type: 'string' },
    dueDate: { type: 'string' },
    tags: { type: 'array', items: { type: 'string' } },
    labels: { type: 'array', items: { type: 'string' } },
    priority: { type: 'string', enum: ['critical', 'high', 'medium', 'low'] },
    taskType: {
      type: 'string',
      enum: ['feature', 'bugfix', 'refactor', 'docs', 'test', 'chore'],
    },
    status: {
      type: 'string',
      enum: [
        'pending',
        'ready',
        'in_progress',
        'blocked',
        'review',
        'completed',
        'failed',
        'archived',
      ],
    },
    order: { type: 'number' },
    query: { type: 'string' },
    limit: { type: 'number' },
    agentId: { type: 'string' },
    name: { type: 'string' },
    role: { type: 'string' },
    provider: { type: 'string' },
    model: { type: 'string' },
    fallbackProfile: { type: 'string' },
    fallbackModels: { type: 'array', items: { type: 'string' } },
    tools: { type: 'array', items: { type: 'string' } },
    allowedCapabilities: { type: 'array', items: { type: 'string' } },
    leaseId: { type: 'string' },
    claimedAt: { type: 'string' },
    heartbeatAt: { type: 'string' },
    leaseExpiresAt: { type: 'string' },
    attempt: { type: 'number' },
    maxAttempts: { type: 'number' },
    subagentId: { type: 'string' },
    runTaskId: { type: 'string' },
    lastResult: { type: 'string' },
    error: { type: 'string' },
    expectedLeaseId: { type: 'string' },
    assignmentStatus: {
      type: 'string',
      enum: ['assigned', 'queued', 'running', 'completed', 'failed', 'cancelled'],
    },
    lifecycleStage: {
      type: 'string',
      enum: ['backlog', 'todo', 'running', 'review', 'done'],
    },
    transitionAction: { type: 'string' },
    transitionComment: { type: 'string' },
    attachmentUrl: { type: 'string' },
    attachmentTitle: { type: 'string' },
    attachmentType: {
      type: 'string',
      enum: ['issue', 'pr', 'doc', 'commit', 'design', 'file', 'url', 'other'],
    },
    releaseStatus: { type: 'string', enum: ['pending', 'ready', 'blocked'] },
    releaseReason: { type: 'string' },
    clearAssignee: { type: 'boolean' },
    recoveryMode: { type: 'string', enum: ['auto', 'release', 'retry', 'fail'] },
    recoveryNow: { type: 'string' },
    recoveryPolicyFailOnCostCeiling: { type: 'boolean' },
    recoveryPolicyReleaseOnFailureKinds: { type: 'array', items: { type: 'string' } },
    recoveryPolicyReleaseOnHeartbeatDue: { type: 'boolean' },
    recoveryPolicyRetryPolicyOverride: {
      type: 'string',
      enum: ['off', 'incremental', 'exponential'],
    },
    assignee: { type: 'string' },
    costCeilingUsd: { type: 'number' },
    retryPolicy: { type: 'string', enum: ['off', 'incremental', 'exponential'] },
    lastFailureKind: { type: 'string' },
    dependsOn: { type: 'array', items: { type: 'string' } },
    estimatedHours: { type: 'number' },
    actualHours: { type: 'number' },
    taskGraph: { type: 'object' },
    graphId: { type: 'string' },
    specId: { type: 'string' },
    specRequirementId: { type: 'string' },
    sourceSystem: { type: 'string' },
    phaseId: { type: 'string' },
    preserveOriginTaskIds: { type: 'boolean' },
    includeArchived: { type: 'boolean' },
    archiveMissingTasks: { type: 'boolean' },
    preserveManualDependencies: { type: 'boolean' },
    dependencyTaskId: { type: 'string' },
    enforceDependencies: { type: 'boolean' },
    childTitles: { type: 'array', items: { type: 'string' } },
    inheritAssignment: { type: 'boolean' },
    inheritLabels: { type: 'boolean' },
    inheritSuccessCriteria: { type: 'boolean' },
    inheritGoalMetrics: { type: 'boolean' },
    inheritDependencies: { type: 'boolean' },
    chainChildren: { type: 'boolean' },
    rewireDependents: { type: 'boolean' },
    closeSourceTasks: { type: 'boolean' },
    metricId: { type: 'string' },
    metricName: { type: 'string' },
    metricTarget: { oneOf: [{ type: 'string' }, { type: 'number' }] },
    metricCurrent: { oneOf: [{ type: 'string' }, { type: 'number' }] },
    metricUnit: { type: 'string' },
    metricStatus: { type: 'string', enum: ['pending', 'met', 'missed', 'waived'] },
    metricNotes: { type: 'string' },
    checkId: { type: 'string' },
    checkDescription: { type: 'string' },
    checkStatus: { type: 'string', enum: ['pending', 'passed', 'failed', 'skipped'] },
    note: { type: 'string' },
    author: { type: 'string' },
    url: { type: 'string' },
    linkTitle: { type: 'string' },
    linkType: {
      type: 'string',
      enum: ['issue', 'pr', 'doc', 'commit', 'design', 'file', 'url', 'other'],
    },
    context: { type: 'string' },
    columns: { type: 'array', items: { type: 'string' } },
    generatedBy: { type: 'string' },
    includeTasks: { type: 'boolean' },
    includeCompletedTasks: { type: 'boolean' },
    preserveAssignment: { type: 'boolean' },
    preserveDependencies: { type: 'boolean' },
    moveTasksToColumnId: { type: 'string' },
    atomicityMode: { type: 'string', enum: ['off', 'assess', 'enforce'] },
    atomicityDecomposition: { type: 'string', enum: ['auto', 'propose'] },
    gateEnforcement: {
      type: 'string',
      // WS-023: `'off'` is deliberately absent. The agent whose work this gate
      // checks must not be able to switch it off; it may only tighten. Turning
      // a gate off stays a human decision, made through board config.
      enum: ['strict', 'soft'],
    },
    subtasks: {
      type: 'array',
      minItems: 2,
      items: {
        type: 'object',
        properties: {
          title: { type: 'string' },
          description: { type: 'string' },
          successCriteria: { type: 'array', items: { type: 'string' } },
          dependsOnIndex: { type: 'array', items: { type: 'number' } },
        },
        required: ['title'],
      },
    },
  },
  required: ['action'],
};
