/**
 * Stateful Kanban domain operations that must execute inside the elected
 * project server. Keep this list explicit: it is both the wire allowlist and
 * the public-client boundary.
 */
export const KANBAN_DOMAIN_OPERATIONS = [
  'createBoard',
  'listBoards',
  'getBoard',
  'updateBoard',
  'removeBoard',
  'duplicateBoard',
  'addColumn',
  'updateColumn',
  'removeColumn',
  'addTask',
  'copyTaskToBoard',
  'transferTaskToBoard',
  'updateTask',
  'moveTask',
  'removeTask',
  'getTask',
  'listKanbanEvents',
  'listTaskActivity',
  'recordTaskActivity',
  'recordTaskFileActivity',
  'addGoalMetricToTask',
  'updateGoalMetricOnTask',
  'addCheckToTask',
  'updateCheckOnTask',
  'addNoteToTask',
  'addLinkToTask',
  'reconcileKanbanBoard',
  'assignTask',
  'updateTaskAssignment',
  'heartbeatTaskAssignment',
  'recoverStaleTaskAssignments',
  'claimReadyTask',
  'releaseTaskClaim',
  'getKanbanOrchestrationSnapshot',
  'getKanbanQueueHealth',
  'addDependency',
  'splitTask',
  'mergeTasks',
  'setTaskChain',
  'getTaskChain',
  'listReadyTasks',
  'createBoardFromTaskGraph',
  'syncBoardFromTaskGraph',
  'exportBoardToTaskGraph',
  'createBoardsFromPhaseGraph',
  'searchKanban',
  'exportBoardMarkdown',
  'adoptManagedLifecycle',
  'repairManagedTaskProjection',
  'transitionTask',
  'touchKanbanPresence',
  'getBoardWithLivePresence',
  'assessTaskAtomicity',
  'proposeTaskDecomposition',
  'resolveDecompositionProposal',
  'verifyTaskCompletion',
  'enforceCompletionGate',
  'attachVerificationReport',
  'finalizeTaskCompletion',
] as const;

export type KanbanDomainOperation = (typeof KANBAN_DOMAIN_OPERATIONS)[number];
