import type { Capabilities, WireFamily } from '@wrongstack/core/types';

export const CAPABILITIES_BY_FAMILY: Record<WireFamily, Capabilities> = {
  anthropic: {
    tools: true,
    parallelTools: true,
    vision: true,
    streaming: true,
    promptCache: true,
    systemPrompt: true,
    jsonMode: false,
    reasoning: false,
    maxContext: 200_000,
    cacheControl: 'native',
    topK: true,
    frequencyPenalty: false,
    presencePenalty: false,
    seed: false,
    structuredOutput: false,
    logprobs: false,
    audio: false,
    multipleCompletions: false,
  },
  openai: {
    tools: true,
    parallelTools: true,
    vision: true,
    streaming: true,
    promptCache: true,
    systemPrompt: true,
    jsonMode: true,
    reasoning: false,
    maxContext: 128_000,
    cacheControl: 'auto',
    topK: false,
    frequencyPenalty: true,
    presencePenalty: true,
    seed: true,
    structuredOutput: true,
    logprobs: true,
    audio: true,
    multipleCompletions: true,
  },
  'openai-compatible': {
    tools: true,
    parallelTools: true,
    vision: false,
    streaming: true,
    promptCache: false,
    systemPrompt: true,
    jsonMode: false,
    reasoning: false,
    maxContext: 0,
    cacheControl: 'none',
    // Conservative — individual presets override per-provider.
    topK: false,
    frequencyPenalty: false,
    presencePenalty: false,
    seed: false,
    structuredOutput: false,
    logprobs: false,
    audio: false,
    multipleCompletions: false,
  },
  // Claude Pro/Max via OAuth (Sign in with Claude). Same wire as anthropic.
  'anthropic-oauth': {
    tools: true,
    parallelTools: true,
    vision: true,
    streaming: true,
    promptCache: true,
    systemPrompt: true,
    jsonMode: false,
    reasoning: false,
    maxContext: 200_000,
    cacheControl: 'native',
    topK: true,
    frequencyPenalty: false,
    presencePenalty: false,
    seed: false,
    structuredOutput: false,
    logprobs: false,
    audio: false,
    multipleCompletions: false,
  },
  // GitHub Copilot subscription (OpenAI chat/completions-compatible wire).
  'github-copilot': {
    tools: true,
    parallelTools: true,
    vision: true,
    streaming: true,
    promptCache: false,
    systemPrompt: true,
    jsonMode: true,
    reasoning: false,
    maxContext: 128_000,
    cacheControl: 'auto',
    topK: false,
    frequencyPenalty: false,
    presencePenalty: false,
    seed: false,
    structuredOutput: false,
    logprobs: false,
    audio: false,
    multipleCompletions: false,
  },
  // ChatGPT-backend Responses API (Sign in with ChatGPT / Codex subscription).
  'openai-codex': {
    tools: true,
    parallelTools: true,
    vision: true,
    streaming: true,
    promptCache: true,
    systemPrompt: true,
    jsonMode: false,
    reasoning: true,
    // Every published Codex model is 1M-windowed (keep in step with the
    // openai-codex block in packages/cli/data/providers.json); the live
    // /codex/models probe caps sessions to the window the backend enforces.
    maxContext: 1_050_000,
    cacheControl: 'auto',
    topK: false,
    frequencyPenalty: false,
    presencePenalty: false,
    seed: false,
    structuredOutput: false,
    logprobs: false,
    audio: false,
    multipleCompletions: false,
  },
  google: {
    tools: true,
    parallelTools: true,
    vision: true,
    streaming: true,
    promptCache: false,
    systemPrompt: true,
    jsonMode: true,
    reasoning: false,
    maxContext: 1_000_000,
    cacheControl: 'none',
    topK: true,
    frequencyPenalty: true,
    presencePenalty: true,
    seed: true,
    structuredOutput: true,
    logprobs: true,
    audio: false,
    multipleCompletions: false,
  },
  unsupported: {
    tools: false,
    parallelTools: false,
    vision: false,
    streaming: false,
    promptCache: false,
    systemPrompt: false,
    jsonMode: false,
    reasoning: false,
    maxContext: 0,
    cacheControl: 'none',
    topK: false,
    frequencyPenalty: false,
    presencePenalty: false,
    seed: false,
    structuredOutput: false,
    logprobs: false,
    audio: false,
    multipleCompletions: false,
  },
};

export function capabilitiesForFamily(
  family: WireFamily,
  overrides: Partial<Capabilities> = {},
): Capabilities {
  return {
    ...(CAPABILITIES_BY_FAMILY[family] ?? CAPABILITIES_BY_FAMILY.unsupported),
    ...overrides,
  };
}
