/**
 * Requirements Intake — domain types.
 *
 * The record model preserves the exact original request verbatim
 * (`originalRequest`) and keeps every derived, normalized, or machine-
 * generated value separate, source-annotated, and user-editable.
 */
import type {
  IntakeAttachmentKind,
  IntakeField,
  IntakeFieldSource,
  IntakePriority,
  IntakeQuestionStatus,
  IntakeStatus,
  RelatedResourceKind,
  RequestType,
  SuggestionKind,
  SuggestionStatus,
} from './constants.js';
import type { VibeProtocolState } from './vibe.js';

/** Actor identity used for authorization and audit. */
export interface IntakeActor {
  /** Stable actor id (user id, agent id, or automation id). */
  id: string;
  /** Actor class. Automation/LLM identities should get minimal permissions. */
  type: 'user' | 'agent' | 'system' | 'automation';
}

/** Per-operation security context. `projectId` is the authorization scope. */
export interface IntakeContext extends IntakeActor {
  /** The project the operation targets. Cross-project access must be denied. */
  projectId: string;
}

/** A supporting file/document/link attached to an intake record. */
export interface IntakeAttachment {
  id: string;
  name: string;
  kind: IntakeAttachmentKind;
  /** Host-resolved path for file-like attachments. */
  path?: string | undefined;
  /** http(s) URL for link-kind attachments. */
  url?: string | undefined;
  sizeBytes?: number | undefined;
  mimeType?: string | undefined;
  source: IntakeFieldSource;
  addedBy?: string | undefined;
  addedAt: number;
}

/** A reference to an existing resource (spec, issue, PR, doc, URL, …). */
export interface RelatedResource {
  id: string;
  kind: RelatedResourceKind;
  /** Resource id, URL, or path. */
  reference: string;
  title?: string | undefined;
  source: IntakeFieldSource;
  addedBy?: string | undefined;
  addedAt: number;
}

/** A structured question/answer pair collected during intake. */
export interface IntakeAnswer {
  id: string;
  /** The intake field this answer fills (see constants.INTAKE_FIELDS). */
  field: string;
  /** Snapshot of the question text at ask time. */
  question: string;
  answer: string;
  source: IntakeFieldSource;
  answeredBy?: string | undefined;
  answeredAt: number;
}

/** A question asked (or offered) during intake. */
export interface IntakeQuestion {
  id: string;
  field: string;
  question: string;
  answer?: string | undefined;
  required: boolean;
  status: IntakeQuestionStatus;
  /** Catalog order — stable across re-derivations. */
  order: number;
}

/** One append-only entry of the record's change history. */
export interface ChangeHistoryEntry {
  at: number;
  actor?: string | undefined;
  actorType?: string | undefined;
  action: string;
  /** Fields whose values changed in this entry. */
  fields?: string[] | undefined;
  from?: IntakeStatus | undefined;
  to?: IntakeStatus | undefined;
}

/** An LLM-generated proposal. Never authoritative until accepted by a user. */
export interface LlmSuggestionProposal {
  id: string;
  kind: SuggestionKind;
  /** Target record field for field-backed kinds (title, request_type, …). */
  field?: string | undefined;
  value: unknown;
  rationale?: string | undefined;
  status: SuggestionStatus;
  createdAt: number;
  resolvedAt?: number | undefined;
}

/** The persistent requirement intake record. */
export interface RequirementIntakeRecord {
  /** `reqi_<ulid>` — stable, generated by the module. */
  id: string;
  /** `proj_<ulid>` project identifier (see core project-identity). */
  projectId: string;
  title: string;
  /** Exact original user request. Immutable after creation. */
  originalRequest: string;
  normalizedSummary: string;
  requestType: RequestType;
  status: IntakeStatus;
  priority: IntakePriority;
  requestedBy: string;
  businessGoal?: string | undefined;
  targetUsers: string[];
  expectedOutcome?: string | undefined;
  scopeNotes?: string | undefined;
  constraints: string[];
  providedContext: string[];
  attachments: IntakeAttachment[];
  relatedResources: RelatedResource[];
  answers: IntakeAnswer[];
  questions: IntakeQuestion[];
  llmSuggestions: LlmSuggestionProposal[];
  metadata: Record<string, unknown>;
  /** True when the request is processed under the Three-Stage VIBE Verification Protocol. */
  isVibeMode?: boolean | undefined;
  /** Persisted state of the VIBE protocol pipeline (Spec-Synthesizer -> Coder -> Auditor). */
  vibeProtocol?: VibeProtocolState | undefined;
  /** Source annotation per record field ('user' | 'llm' | 'deterministic'). */
  fieldSources: Partial<Record<IntakeField, IntakeFieldSource>>;
  /** Raw idempotency key used at creation (kept for diagnostics). */
  idempotencyKey?: string | undefined;
  /** Optimistic-concurrency counter; every write increments it. */
  version: number;
  history: ChangeHistoryEntry[];
  createdAt: number;
  updatedAt: number;
  submittedAt?: number | undefined;
  submittedBy?: string | undefined;
  submittedByType?: string | undefined;
  cancelledAt?: number | undefined;
  cancelledReason?: string | undefined;
  archivedAt?: number | undefined;
}

/** Payload for creating an intake record. */
export interface CreateIntakeInput {
  projectId: string;
  /** Exact original request. Required, non-blank, ≤ MAX_REQUEST_LENGTH. */
  originalRequest: string;
  title?: string | undefined;
  /** Any string is accepted and normalized; unknown values become 'other'. */
  requestType?: string | undefined;
  priority?: IntakePriority | undefined;
  requestedBy: string;
  businessGoal?: string | undefined;
  targetUsers?: string[] | undefined;
  expectedOutcome?: string | undefined;
  scopeNotes?: string | undefined;
  constraints?: string[] | undefined;
  providedContext?: string[] | undefined;
  attachments?: IntakeAttachmentInput[] | undefined;
  relatedResources?: RelatedResourceInput[] | undefined;
  metadata?: Record<string, unknown> | undefined;
  /** Explicit override for Vibe Mode; if omitted, automatically detected from originalRequest. */
  isVibeMode?: boolean | undefined;
  /** Optional initial vibe state if resuming an existing cycle. */
  vibeProtocol?: VibeProtocolState | undefined;
  /** Idempotent-create key: same key + project returns the existing record. */
  idempotencyKey?: string | undefined;
  /**
   * Fields already answerable from existing project data. Their questions
   * are skipped instead of asked.
   */
  knownFields?: string[] | undefined;
  /** Question catalog override. Defaults to DEFAULT_INTAKE_QUESTIONS. */
  questions?: IntakeQuestionTemplateInput[] | undefined;
}

export interface IntakeAttachmentInput {
  name: string;
  kind: IntakeAttachmentKind;
  path?: string | undefined;
  url?: string | undefined;
  sizeBytes?: number | undefined;
  mimeType?: string | undefined;
}

export interface RelatedResourceInput {
  kind: RelatedResourceKind;
  reference: string;
  title?: string | undefined;
}

export interface IntakeQuestionTemplateInput {
  field: string;
  question: string;
  required?: boolean | undefined;
}

/** Payload for updating a draft intake record. */
export interface UpdateIntakeInput {
  title?: string | undefined;
  requestType?: string | undefined;
  priority?: IntakePriority | undefined;
  businessGoal?: string | undefined;
  targetUsers?: string[] | undefined;
  expectedOutcome?: string | undefined;
  scopeNotes?: string | undefined;
  constraints?: string[] | undefined;
  providedContext?: string[] | undefined;
  metadata?: Record<string, unknown> | undefined;
  isVibeMode?: boolean | undefined;
  vibeProtocol?: VibeProtocolState | undefined;
}

/** Payload for answering an intake question. */
export interface AddAnswerInput {
  field: string;
  answer: string;
  question?: string | undefined;
}

/** Payload for attaching a supporting resource. */
export interface AttachResourceInput {
  attachment?: IntakeAttachmentInput | undefined;
  relatedResource?: RelatedResourceInput | undefined;
}

/** Domain events published by the service. */
export const INTAKE_EVENT_NAMES = [
  'RequirementIntakeCreated',
  'RequirementIntakeUpdated',
  'RequirementIntakeInformationRequested',
  'RequirementIntakeSubmitted',
  'RequirementIntakeCancelled',
  'RequirementIntakeArchived',
] as const;

export type IntakeEventName = (typeof INTAKE_EVENT_NAMES)[number];

/**
 * Event payload. Carries identifiers and safe metadata only — never a copy
 * of the user request.
 */
export interface IntakeEvent {
  event: IntakeEventName;
  intakeId: string;
  projectId: string;
  actorId?: string | undefined;
  actorType?: string | undefined;
  previousStatus?: IntakeStatus | undefined;
  status: IntakeStatus;
  timestamp: string;
}
