export type SettingsMode = 'off' | 'suggest' | 'auto';
export type LogLevel = 'error' | 'warn' | 'info' | 'debug' | 'trace';
export type AuditLevel = 'minimal' | 'standard' | 'full';
export type CompactorStrategy = 'hybrid' | 'intelligent' | 'selective';
export type ContextMode = 'balanced' | 'frugal' | 'deep';
export type StatuslineMode = 'minimum' | 'detailed' | 'no-color';
export type ReasoningMode = 'auto' | 'on' | 'off';
export type ReasoningEffort = 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max';
export type CacheTtl = 'default' | '5m' | '1h';
export type EnhanceLanguage = 'original' | 'english';
export type TokenSavingTierTui = 'auto' | 'off' | 'minimal' | 'light' | 'medium' | 'aggressive';
export type FleetChatVerbosityTui = 'off' | 'full';
export type ConfigScope = 'global' | 'project';
export type AnimationStyleChoice = 'rainbow' | 'wave' | 'pulse' | 'dots' | 'breathe' | 'cycle';

export type SettingsPickerPatch = Partial<{
  mode: SettingsMode;
  delayMs: number;
  titleAnimation: boolean;
  yolo: boolean;
  fleetChat: FleetChatVerbosityTui;
  chime: boolean;
  confirmExit: boolean;
  nextPrediction: boolean;
  featureMcp: boolean;
  featurePlugins: boolean;
  featureMemory: boolean;
  featureSkills: boolean;
  featureModelsRegistry: boolean;
  tokenSavingTier: TokenSavingTierTui;
  allowOutsideProjectRoot: boolean;
  contextAutoCompact: boolean;
  contextStrategy: CompactorStrategy;
  contextMode: ContextMode;
  maxConcurrent: number;
  logLevel: LogLevel;
  auditLevel: AuditLevel;
  indexOnStart: boolean;
  multiDiffSummaryThreshold: number;
  maxIterations: number;
  autoProceedMaxIterations: number;
  enhanceDelayMs: number;
  enhanceEnabled: boolean;
  enhanceLanguage: EnhanceLanguage;
  debugStream: boolean;
  statuslineMode: StatuslineMode;
  reasoningMode: ReasoningMode;
  reasoningEffort: ReasoningEffort;
  reasoningPreserve: boolean;
  thinkingWord: string;
  cacheTtl: CacheTtl;
  configScope: ConfigScope;
  animationStyle: AnimationStyleChoice;
  breakerEnabled: boolean;
  breakerAutoKillResetMs: number;
  showModelReasoning: boolean;
  showAgentSwarmPanel: boolean;
}>;
