import type {
  Message,
  SessionMarker,
  SessionTimelineEntry,
  SessionTimelineImage,
  SessionToolMeta,
} from '@wrongstack/webui-protocol';
import { projectSessionTimeline } from '@wrongstack/webui-protocol';
import type { ChatMessage, SimpleSubagent, ToolCallInfo } from '../types.js';

/**
 * Re-exported, never re-declared.
 *
 * This module used to keep its OWN copy of the prefix list, which promptly
 * drifted: core stopped hiding the `[SESSION RESUME …]` notices (they are
 * written for the human, not the model) and this copy went on hiding them.
 * One list, in core.
 */
export { isSystemInjectedMessage, SYSTEM_INJECTION_PREFIXES } from '@wrongstack/webui-protocol';

export const SIMPLE_CHAT_MAX_MESSAGES = 600;
export const SIMPLE_CHAT_MAX_RETAINED_BYTES = 32 * 1024 * 1024;
export const SIMPLE_CHAT_MAX_TEXT_CHARS = 2 * 1024 * 1024;

interface SimpleChatRetentionBudget {
  maxMessages?: number;
  maxBytes?: number;
  maxTextChars?: number;
}

/** Keep both ends of pathological provider output while bounding its heap. */
export function boundSimpleChatText(text: string, maxChars = SIMPLE_CHAT_MAX_TEXT_CHARS): string {
  if (text.length <= maxChars) return text;
  const marker = '\n\n… [older streamed text omitted to protect memory] …\n\n';
  if (maxChars <= marker.length) {
    const head = Math.ceil(maxChars / 2);
    return text.slice(0, head) + text.slice(text.length - (maxChars - head));
  }
  const available = Math.max(0, maxChars - marker.length);
  const head = Math.ceil(available / 2);
  return text.slice(0, head) + marker + text.slice(text.length - (available - head));
}

function retainedMessageBytes(message: ChatMessage): number {
  let bytes = message.text.length * 2 + 256;
  for (const image of message.images ?? []) {
    bytes += image.data.length * 2 + image.mime.length * 2 + 64;
  }
  return bytes;
}

/**
 * Bound the visible transcript by both count and approximate UTF-16 heap
 * bytes. A count-only cap still permits a few giant replay/vision rows to pin
 * hundreds of MB. The persisted session remains the complete source of truth.
 */
export function retainSimpleChatMessages(
  messages: readonly ChatMessage[],
  budget: SimpleChatRetentionBudget = {},
): ChatMessage[] {
  const maxMessages = Math.max(1, Math.floor(budget.maxMessages ?? SIMPLE_CHAT_MAX_MESSAGES));
  const maxBytes = Math.max(1, Math.floor(budget.maxBytes ?? SIMPLE_CHAT_MAX_RETAINED_BYTES));
  const maxTextChars = Math.max(1, Math.floor(budget.maxTextChars ?? SIMPLE_CHAT_MAX_TEXT_CHARS));
  const retained: ChatMessage[] = [];
  let bytes = 0;

  for (let index = messages.length - 1; index >= 0 && retained.length < maxMessages; index -= 1) {
    const source = messages[index]!;
    let message: ChatMessage =
      source.text.length > maxTextChars
        ? { ...source, text: boundSimpleChatText(source.text, maxTextChars) }
        : source;
    let messageBytes = retainedMessageBytes(message);
    if (messageBytes > maxBytes && message.images?.length) {
      message = { ...message, images: undefined };
      messageBytes = retainedMessageBytes(message);
    }
    if (retained.length > 0 && bytes + messageBytes > maxBytes) break;
    retained.push(message);
    bytes += messageBytes;
  }

  retained.reverse();
  return retained;
}

function blockText(block: unknown): string {
  if (typeof block === 'string') return block;
  if (!block || typeof block !== 'object') return '';
  const value = block as Record<string, unknown>;
  if (typeof value['text'] === 'string') return value['text'];
  if (typeof value['content'] === 'string') return value['content'];
  if (Array.isArray(value['content'])) return contentToText(value['content']);
  return '';
}

/** Convert canonical provider/session content blocks into safe display text. */
export function contentToText(content: unknown): string {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) return content.map(blockText).filter(Boolean).join('\n\n');
  return blockText(content);
}

/**
 * Rebuild the visible chat history from a `session.start` replay.
 *
 * `markers` carries the audit timeline (compaction, mode/skill switches,
 * subagent lifecycle, provider retries, truncation) projected server-side.
 * They are interleaved by timestamp so a page refresh shows the same events
 * the live stream did. Ties keep the conversation message first, and a
 * message with no `ts` does not advance the marker cursor — the same merge
 * rule the TUI resume renderer uses.
 *
 * Note the injection filter deliberately applies to conversation entries
 * only: markers are generated by this projection, not folded into the
 * conversation by the agent loop, so they never look like fake user input.
 */
export function replayToMessages(
  replay: unknown,
  markers?: unknown,
  toolMeta?: unknown,
): ChatMessage[] {
  const out: ChatMessage[] = [];
  for (const [index, item] of replayTimeline(replay, markers, toolMeta).entries()) {
    // Tool calls live in their own list here (the accordion beside the chat),
    // so the timeline's tool entries are consumed by `replayToToolCalls`.
    if (item.kind === 'tool') continue;
    if (item.kind === 'marker') {
      if (!item.text) continue;
      out.push({
        id: `replay-marker-${index}`,
        role: 'system',
        text: item.text,
        ts: item.ts,
        replayOrder: index,
      });
      continue;
    }
    if (item.kind === 'thinking') {
      out.push({
        id: `replay-thinking-${index}`,
        role: 'thinking',
        text: item.text,
        ts: item.ts,
        replayOrder: index,
      });
      continue;
    }
    if (!item.text && item.kind !== 'user') continue;
    out.push({
      id: `replay-${index}`,
      role: item.kind === 'assistant' ? 'assistant' : item.kind === 'system' ? 'system' : 'user',
      text: item.text,
      ts: item.ts,
      replayOrder: index,
      ...(item.kind === 'assistant' ? { final: item.final } : {}),
      ...(item.kind === 'user' && item.images
        ? {
            images: item.images.flatMap((image: SessionTimelineImage) =>
              image.data ? [{ data: image.data, mime: image.mediaType ?? 'image/png' }] : [],
            ),
          }
        : {}),
    } satisfies ChatMessage);
  }

  return retainSimpleChatMessages(out);
}

export function replayToToolCalls(replay: unknown, toolMeta?: unknown): ToolCallInfo[] {
  const calls: ToolCallInfo[] = [];
  for (const [index, item] of replayTimeline(replay, undefined, toolMeta).entries()) {
    if (item.kind !== 'tool') continue;
    calls.push({
      id: item.toolUseId || `replay-tool-${index}`,
      name: item.name,
      input: item.input,
      replayOrder: index,
      // A call the journal never resolved stays RUNNING. Forcing it to
      // `error` here made every crash-interrupted tool — and the tool a
      // still-live run is executing right now — replay as a failure.
      status: item.ok === undefined ? 'running' : item.ok ? 'done' : 'error',
      ...(item.ok !== undefined ? { ok: item.ok } : {}),
      ...(item.output !== undefined ? { output: item.output } : {}),
      ...(item.durationMs !== undefined ? { durationMs: item.durationMs } : {}),
      ts: item.ts,
    });
  }
  return calls;
}

/**
 * Project one `session.start` replay into the shared timeline.
 *
 * Ordering, tool pairing and the system-injection filter come from core's
 * {@link projectSessionTimeline} — the same function the TUI, WebUI and HQ go
 * through — so the SimpleUI cannot drift from them on what a resumed session
 * looks like.
 *
 * `textBlocks: 'split'` is deliberately the canonical restore behaviour. If
 * a model wrote prose, called a tool, then wrote more prose in the same
 * provider message, resume must put the tool back between those two prose
 * runs. SimpleUI still keeps a sidebar copy of tools, but the chat timeline is
 * ordered from this projection.
 */
function replayTimeline(
  replay: unknown,
  markers?: unknown,
  toolMeta?: unknown,
): SessionTimelineEntry[] {
  if (!Array.isArray(replay)) return [];
  const messages = replay.filter(
    (entry): entry is Message =>
      !!entry &&
      typeof entry === 'object' &&
      ((entry as Message).role === 'user' ||
        (entry as Message).role === 'assistant' ||
        (entry as Message).role === 'system'),
  );
  return projectSessionTimeline({
    messages,
    markers: Array.isArray(markers)
      ? (markers as SessionMarker[]).filter((marker) => !isSubagentResumeMarker(marker.source))
      : [],
    toolMeta: Array.isArray(toolMeta) ? (toolMeta as SessionToolMeta[]) : [],
    thinkingPlacement: 'inline',
    textBlocks: 'split',
    textSeparator: '\n\n',
  });
}

const SUBAGENT_RESUME_MARKER_SOURCES = new Set<string>([
  'agent_spawned',
  'agent_session_linked',
  'agent_stopped',
  'agent_error',
  'delegate_started',
  'delegate_completed',
]);

function isSubagentResumeMarker(source: string): boolean {
  return SUBAGENT_RESUME_MARKER_SOURCES.has(source);
}

function upsert(
  agents: SimpleSubagent[],
  id: string,
  patch: Partial<SimpleSubagent>,
): SimpleSubagent[] {
  if (!id || id === 'leader') return agents;
  const current = agents.find((agent) => agent.id === id);
  if (!current) return [...agents, { id, name: id, status: 'idle', ...patch }];
  return agents.map((agent) => (agent.id === id ? { ...agent, ...patch } : agent));
}

/** Apply the intentionally small subagent projection used by the header strip. */
export function updateSubagents(
  agents: SimpleSubagent[],
  payload: Record<string, unknown>,
): SimpleSubagent[] {
  const id = typeof payload['subagentId'] === 'string' ? payload['subagentId'] : '';
  const kind = typeof payload['kind'] === 'string' ? payload['kind'] : '';
  if (kind === 'removed') return agents.filter((agent) => agent.id !== id);

  const task =
    typeof payload['description'] === 'string'
      ? payload['description']
      : typeof payload['task'] === 'string'
        ? payload['task']
        : undefined;
  if (kind === 'spawned') {
    return upsert(agents, id, {
      name: typeof payload['name'] === 'string' ? payload['name'] : id,
      status: 'idle',
      task,
      model: typeof payload['model'] === 'string' ? payload['model'] : undefined,
    });
  }
  if (kind === 'task_started') return upsert(agents, id, { status: 'running', task });
  if (kind === 'task_completed') {
    const status = typeof payload['status'] === 'string' ? payload['status'] : 'completed';
    return upsert(agents, id, { status, task: undefined });
  }
  return upsert(agents, id, {});
}
