import type { ChatMessage, SimpleSubagent } from '../types.js';

function blockText(block: unknown): string {
  if (typeof block === 'string') return block;
  if (!block || typeof block !== 'object') return '';
  const value = block as Record<string, unknown>;
  if (typeof value['text'] === 'string') return value['text'];
  if (typeof value['content'] === 'string') return value['content'];
  if (Array.isArray(value['content'])) return contentToText(value['content']);
  return '';
}

/** Convert canonical provider/session content blocks into safe display text. */
export function contentToText(content: unknown): string {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) return content.map(blockText).filter(Boolean).join('\n\n');
  return blockText(content);
}

/**
 * Extract only text content from replay message content blocks, filtering out
 * tool_use, tool_result, thinking, and image blocks that should not appear as
 * visible assistant text in the conversation.
 *
 * During session replay, assistant messages may have mixed ContentBlock[]
 * where tool_use and tool_result blocks are interleaved with text blocks.
 * This function keeps only blocks where `type === 'text'`, aligning replay
 * rendering with the live streaming path (where tool calls are tracked
 * separately in `toolCalls` state and rendered as a grouped accordion at
 * the bottom of the conversation).
 */
function replayTextContent(content: unknown): string {
  if (typeof content === 'string') return content.trim();
  if (Array.isArray(content)) {
    return content
      .filter(
        (block): block is { type: 'text'; text: string } =>
          typeof block === 'object' &&
          block !== null &&
          (block as Record<string, unknown>)['type'] === 'text' &&
          typeof (block as Record<string, unknown>)['text'] === 'string',
      )
      .map((block) => block.text)
      .join('\n\n')
      .trim();
  }
  return '';
}

/**
 * System-injected metadata prefixes that are folded into the conversation
 * as `user`-role messages by the agent loop but should NOT appear in the
 * human-facing chat history on session replay.  These blocks exist so the
 * LLM sees mailbox / BTW / fleet-pulse / loop-detector content at runtime;
 * they are not real user input.
 *
 * All prefixes generated by our own core code with fixed casing, so an
 * exact trimmed-startswith match is sufficient — no regex overhead
 * needed on potentially large replay arrays.
 */
const SYSTEM_INJECTION_PREFIXES = [
  '[MAILBOX]',
  '[MAILBOX BTW]',
  '[BY THE WAY —',
  '[QUEUED MESSAGES —',
  '[FLEET PULSE]',
  '[loop-detector]',
];

function isSystemInjected(text: string): boolean {
  const trimmed = text.trimStart();
  for (const prefix of SYSTEM_INJECTION_PREFIXES) {
    if (trimmed.startsWith(prefix)) return true;
  }
  return false;
}

/**
 * Rebuild the visible chat history from a `session.start` replay.
 *
 * `markers` carries the audit timeline (compaction, mode/skill switches,
 * subagent lifecycle, provider retries, truncation) projected server-side.
 * They are interleaved by timestamp so a page refresh shows the same events
 * the live stream did. Ties keep the conversation message first, and a
 * message with no `ts` does not advance the marker cursor — the same merge
 * rule the TUI resume renderer uses.
 *
 * Note the injection filter deliberately applies to conversation entries
 * only: markers are generated by this projection, not folded into the
 * conversation by the agent loop, so they never look like fake user input.
 */
export function replayToMessages(replay: unknown, markers?: unknown): ChatMessage[] {
  if (!Array.isArray(replay)) return [];
  const markerList = Array.isArray(markers) ? markers : [];
  const out: ChatMessage[] = [];
  let markerIndex = 0;

  const pushMarker = (marker: Record<string, unknown>, index: number): void => {
    const text = typeof marker['text'] === 'string' ? marker['text'] : '';
    if (!text) return;
    out.push({
      id: `replay-marker-${index}`,
      role: 'system',
      text,
      ts: typeof marker['ts'] === 'string' ? marker['ts'] : undefined,
    } satisfies ChatMessage);
  };
  const markerTs = (index: number): string | undefined => {
    const marker = markerList[index];
    if (!marker || typeof marker !== 'object') return undefined;
    const ts = (marker as Record<string, unknown>)['ts'];
    return typeof ts === 'string' ? ts : undefined;
  };
  const flushMarkersBefore = (boundary: unknown): void => {
    if (typeof boundary !== 'string') return;
    for (;;) {
      const ts = markerTs(markerIndex);
      if (ts === undefined || ts >= boundary) break;
      pushMarker(markerList[markerIndex] as Record<string, unknown>, markerIndex);
      markerIndex += 1;
    }
  };

  for (const [index, entry] of replay.entries()) {
    if (!entry || typeof entry !== 'object') continue;
    const value = entry as Record<string, unknown>;
    flushMarkersBefore(value['ts']);
    const role = value['role'];
    if (role !== 'user' && role !== 'assistant' && role !== 'system') continue;
    const text = replayTextContent(value['content']);
    if (!text) continue;
    // Filter out system-injected metadata blocks that were folded into the
    // conversation by the agent loop (mailbox, BTW, fleet-pulse, loop-
    // detector).  These exist for the LLM at runtime; the human does not
    // need to re-read them on page refresh.
    if (isSystemInjected(text)) continue;
    out.push({
      id: `replay-${index}`,
      role,
      text,
      ts: typeof value['ts'] === 'string' ? value['ts'] : undefined,
    } satisfies ChatMessage);
  }

  while (markerIndex < markerList.length) {
    const marker = markerList[markerIndex];
    if (marker && typeof marker === 'object') {
      pushMarker(marker as Record<string, unknown>, markerIndex);
    }
    markerIndex += 1;
  }

  return out;
}

function upsert(
  agents: SimpleSubagent[],
  id: string,
  patch: Partial<SimpleSubagent>,
): SimpleSubagent[] {
  if (!id || id === 'leader') return agents;
  const current = agents.find((agent) => agent.id === id);
  if (!current) return [...agents, { id, name: id, status: 'idle', ...patch }];
  return agents.map((agent) => (agent.id === id ? { ...agent, ...patch } : agent));
}

/** Apply the intentionally small subagent projection used by the header strip. */
export function updateSubagents(
  agents: SimpleSubagent[],
  payload: Record<string, unknown>,
): SimpleSubagent[] {
  const id = typeof payload['subagentId'] === 'string' ? payload['subagentId'] : '';
  const kind = typeof payload['kind'] === 'string' ? payload['kind'] : '';
  if (kind === 'removed') return agents.filter((agent) => agent.id !== id);

  const task =
    typeof payload['description'] === 'string'
      ? payload['description']
      : typeof payload['task'] === 'string'
        ? payload['task']
        : undefined;
  if (kind === 'spawned') {
    return upsert(agents, id, {
      name: typeof payload['name'] === 'string' ? payload['name'] : id,
      status: 'idle',
      task,
      model: typeof payload['model'] === 'string' ? payload['model'] : undefined,
    });
  }
  if (kind === 'task_started') return upsert(agents, id, { status: 'running', task });
  if (kind === 'task_completed') {
    const status = typeof payload['status'] === 'string' ? payload['status'] : 'completed';
    return upsert(agents, id, { status, task: undefined });
  }
  return upsert(agents, id, {});
}
